//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHITERP.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FinFusionEntities : DbContext
    {
        public FinFusionEntities()
            : base("name=FinFusionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<VW_USER_DETAILS> VW_USER_DETAILS { get; set; }
        public virtual DbSet<VW_CUSTOMER_LOCATION_CBX_ASSGN> VW_CUSTOMER_LOCATION_CBX_ASSGN { get; set; }
    
        public virtual ObjectResult<PR_ACCOUNTINGYEAR_ID_CHK_Result> PR_ACCOUNTINGYEAR_ID_CHK(Nullable<int> pFYear, Nullable<int> pTYear)
        {
            var pFYearParameter = pFYear.HasValue ?
                new ObjectParameter("PFYear", pFYear) :
                new ObjectParameter("PFYear", typeof(int));
    
            var pTYearParameter = pTYear.HasValue ?
                new ObjectParameter("PTYear", pTYear) :
                new ObjectParameter("PTYear", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PR_ACCOUNTINGYEAR_ID_CHK_Result>("PR_ACCOUNTINGYEAR_ID_CHK", pFYearParameter, pTYearParameter);
        }
    
        public virtual ObjectResult<pr_Chit_Subscription_Organization_Name_Assgn_Result> pr_Chit_Subscription_Organization_Name_Assgn()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Chit_Subscription_Organization_Name_Assgn_Result>("pr_Chit_Subscription_Organization_Name_Assgn");
        }
    
        public virtual ObjectResult<pr_Chit_Subscription_Scheme_Detail_Assgn_Result> pr_Chit_Subscription_Scheme_Detail_Assgn(Nullable<int> pChitSchemeID)
        {
            var pChitSchemeIDParameter = pChitSchemeID.HasValue ?
                new ObjectParameter("PChitSchemeID", pChitSchemeID) :
                new ObjectParameter("PChitSchemeID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Chit_Subscription_Scheme_Detail_Assgn_Result>("pr_Chit_Subscription_Scheme_Detail_Assgn", pChitSchemeIDParameter);
        }
    
        public virtual ObjectResult<PR_COMPANYACCOUNTINGDETAIL_ID_CHK_Result> PR_COMPANYACCOUNTINGDETAIL_ID_CHK(Nullable<int> pCompId, Nullable<int> pYrId)
        {
            var pCompIdParameter = pCompId.HasValue ?
                new ObjectParameter("PCompId", pCompId) :
                new ObjectParameter("PCompId", typeof(int));
    
            var pYrIdParameter = pYrId.HasValue ?
                new ObjectParameter("PYrId", pYrId) :
                new ObjectParameter("PYrId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PR_COMPANYACCOUNTINGDETAIL_ID_CHK_Result>("PR_COMPANYACCOUNTINGDETAIL_ID_CHK", pCompIdParameter, pYrIdParameter);
        }
    
        public virtual ObjectResult<pr_db_monthwise_summary_Result> pr_db_monthwise_summary(string usrid, Nullable<int> empid, Nullable<System.DateTime> fdt, Nullable<System.DateTime> tdt, Nullable<int> prod)
        {
            var usridParameter = usrid != null ?
                new ObjectParameter("usrid", usrid) :
                new ObjectParameter("usrid", typeof(string));
    
            var empidParameter = empid.HasValue ?
                new ObjectParameter("empid", empid) :
                new ObjectParameter("empid", typeof(int));
    
            var fdtParameter = fdt.HasValue ?
                new ObjectParameter("fdt", fdt) :
                new ObjectParameter("fdt", typeof(System.DateTime));
    
            var tdtParameter = tdt.HasValue ?
                new ObjectParameter("tdt", tdt) :
                new ObjectParameter("tdt", typeof(System.DateTime));
    
            var prodParameter = prod.HasValue ?
                new ObjectParameter("prod", prod) :
                new ObjectParameter("prod", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_db_monthwise_summary_Result>("pr_db_monthwise_summary", usridParameter, empidParameter, fdtParameter, tdtParameter, prodParameter);
        }
    
        public virtual ObjectResult<pr_db_today_Summary_Result> pr_db_today_Summary(string usrid, Nullable<int> empid, Nullable<System.DateTime> fdt, Nullable<System.DateTime> tdt, Nullable<int> prod)
        {
            var usridParameter = usrid != null ?
                new ObjectParameter("usrid", usrid) :
                new ObjectParameter("usrid", typeof(string));
    
            var empidParameter = empid.HasValue ?
                new ObjectParameter("empid", empid) :
                new ObjectParameter("empid", typeof(int));
    
            var fdtParameter = fdt.HasValue ?
                new ObjectParameter("fdt", fdt) :
                new ObjectParameter("fdt", typeof(System.DateTime));
    
            var tdtParameter = tdt.HasValue ?
                new ObjectParameter("tdt", tdt) :
                new ObjectParameter("tdt", typeof(System.DateTime));
    
            var prodParameter = prod.HasValue ?
                new ObjectParameter("prod", prod) :
                new ObjectParameter("prod", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_db_today_Summary_Result>("pr_db_today_Summary", usridParameter, empidParameter, fdtParameter, tdtParameter, prodParameter);
        }
    
        public virtual ObjectResult<pr_Get_Book_PickupDay_Result> pr_Get_Book_PickupDay(Nullable<int> dval)
        {
            var dvalParameter = dval.HasValue ?
                new ObjectParameter("dval", dval) :
                new ObjectParameter("dval", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Get_Book_PickupDay_Result>("pr_Get_Book_PickupDay", dvalParameter);
        }
    
        public virtual ObjectResult<pr_Get_Chit_Group_Subscribers_Dtl_Result> pr_Get_Chit_Group_Subscribers_Dtl(Nullable<int> chitgroupid)
        {
            var chitgroupidParameter = chitgroupid.HasValue ?
                new ObjectParameter("chitgroupid", chitgroupid) :
                new ObjectParameter("chitgroupid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Get_Chit_Group_Subscribers_Dtl_Result>("pr_Get_Chit_Group_Subscribers_Dtl", chitgroupidParameter);
        }
    
        public virtual ObjectResult<pr_Get_Client_Type_Result> pr_Get_Client_Type(Nullable<int> dval)
        {
            var dvalParameter = dval.HasValue ?
                new ObjectParameter("dval", dval) :
                new ObjectParameter("dval", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Get_Client_Type_Result>("pr_Get_Client_Type", dvalParameter);
        }
    
        public virtual ObjectResult<pr_Get_Contact_Type_Result> pr_Get_Contact_Type(Nullable<int> dval)
        {
            var dvalParameter = dval.HasValue ?
                new ObjectParameter("dval", dval) :
                new ObjectParameter("dval", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Get_Contact_Type_Result>("pr_Get_Contact_Type", dvalParameter);
        }
    
        public virtual ObjectResult<pr_Get_Employee_Dtl_Result> pr_Get_Employee_Dtl(string usrid)
        {
            var usridParameter = usrid != null ?
                new ObjectParameter("usrid", usrid) :
                new ObjectParameter("usrid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Get_Employee_Dtl_Result>("pr_Get_Employee_Dtl", usridParameter);
        }
    
        public virtual ObjectResult<pr_Get_Loan_Schedule_n_Collection_Details_Result> pr_Get_Loan_Schedule_n_Collection_Details(Nullable<int> loanSubsID, string usrid)
        {
            var loanSubsIDParameter = loanSubsID.HasValue ?
                new ObjectParameter("LoanSubsID", loanSubsID) :
                new ObjectParameter("LoanSubsID", typeof(int));
    
            var usridParameter = usrid != null ?
                new ObjectParameter("usrid", usrid) :
                new ObjectParameter("usrid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Get_Loan_Schedule_n_Collection_Details_Result>("pr_Get_Loan_Schedule_n_Collection_Details", loanSubsIDParameter, usridParameter);
        }
    
        public virtual ObjectResult<pr_Get_Master_Category_Result> pr_Get_Master_Category(string categorydesc)
        {
            var categorydescParameter = categorydesc != null ?
                new ObjectParameter("categorydesc", categorydesc) :
                new ObjectParameter("categorydesc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Get_Master_Category_Result>("pr_Get_Master_Category", categorydescParameter);
        }
    
        public virtual ObjectResult<pr_Get_ProductCategory_Result> pr_Get_ProductCategory(string usrid, Nullable<int> empid, Nullable<int> prod, string trncateg)
        {
            var usridParameter = usrid != null ?
                new ObjectParameter("usrid", usrid) :
                new ObjectParameter("usrid", typeof(string));
    
            var empidParameter = empid.HasValue ?
                new ObjectParameter("empid", empid) :
                new ObjectParameter("empid", typeof(int));
    
            var prodParameter = prod.HasValue ?
                new ObjectParameter("prod", prod) :
                new ObjectParameter("prod", typeof(int));
    
            var trncategParameter = trncateg != null ?
                new ObjectParameter("trncateg", trncateg) :
                new ObjectParameter("trncateg", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Get_ProductCategory_Result>("pr_Get_ProductCategory", usridParameter, empidParameter, prodParameter, trncategParameter);
        }
    
        public virtual ObjectResult<pr_Get_ProductSubsDefValDetl_Result> pr_Get_ProductSubsDefValDetl(Nullable<int> prod, Nullable<int> subsid)
        {
            var prodParameter = prod.HasValue ?
                new ObjectParameter("prod", prod) :
                new ObjectParameter("prod", typeof(int));
    
            var subsidParameter = subsid.HasValue ?
                new ObjectParameter("subsid", subsid) :
                new ObjectParameter("subsid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Get_ProductSubsDefValDetl_Result>("pr_Get_ProductSubsDefValDetl", prodParameter, subsidParameter);
        }
    
        public virtual ObjectResult<pr_Get_QRCode_Loan_Subscription_Dtl_Result> pr_Get_QRCode_Loan_Subscription_Dtl(string usrid, Nullable<int> empid, Nullable<int> subsid)
        {
            var usridParameter = usrid != null ?
                new ObjectParameter("usrid", usrid) :
                new ObjectParameter("usrid", typeof(string));
    
            var empidParameter = empid.HasValue ?
                new ObjectParameter("empid", empid) :
                new ObjectParameter("empid", typeof(int));
    
            var subsidParameter = subsid.HasValue ?
                new ObjectParameter("subsid", subsid) :
                new ObjectParameter("subsid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Get_QRCode_Loan_Subscription_Dtl_Result>("pr_Get_QRCode_Loan_Subscription_Dtl", usridParameter, empidParameter, subsidParameter);
        }
    
        public virtual ObjectResult<pr_Get_Subscription_Info_Result> pr_Get_Subscription_Info(string usrid, Nullable<int> empid, Nullable<int> prod)
        {
            var usridParameter = usrid != null ?
                new ObjectParameter("usrid", usrid) :
                new ObjectParameter("usrid", typeof(string));
    
            var empidParameter = empid.HasValue ?
                new ObjectParameter("empid", empid) :
                new ObjectParameter("empid", typeof(int));
    
            var prodParameter = prod.HasValue ?
                new ObjectParameter("prod", prod) :
                new ObjectParameter("prod", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Get_Subscription_Info_Result>("pr_Get_Subscription_Info", usridParameter, empidParameter, prodParameter);
        }
    
        public virtual ObjectResult<pr_Get_Today_Collection_Result> pr_Get_Today_Collection(Nullable<System.DateTime> indt, string usrid, Nullable<int> empid, Nullable<int> prod)
        {
            var indtParameter = indt.HasValue ?
                new ObjectParameter("indt", indt) :
                new ObjectParameter("indt", typeof(System.DateTime));
    
            var usridParameter = usrid != null ?
                new ObjectParameter("usrid", usrid) :
                new ObjectParameter("usrid", typeof(string));
    
            var empidParameter = empid.HasValue ?
                new ObjectParameter("empid", empid) :
                new ObjectParameter("empid", typeof(int));
    
            var prodParameter = prod.HasValue ?
                new ObjectParameter("prod", prod) :
                new ObjectParameter("prod", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Get_Today_Collection_Result>("pr_Get_Today_Collection", indtParameter, usridParameter, empidParameter, prodParameter);
        }
    
        public virtual ObjectResult<pr_Get_Transaction_Dtl_Result> pr_Get_Transaction_Dtl(string categ, Nullable<int> id)
        {
            var categParameter = categ != null ?
                new ObjectParameter("categ", categ) :
                new ObjectParameter("categ", typeof(string));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Get_Transaction_Dtl_Result>("pr_Get_Transaction_Dtl", categParameter, idParameter);
        }
    
        public virtual ObjectResult<pr_search_category_master_Result> pr_search_category_master(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_search_category_master_Result>("pr_search_category_master", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount);
        }
    
        public virtual ObjectResult<pr_Search_Company_OfficeMaster_Result> pr_Search_Company_OfficeMaster(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, string cUSRID)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var cUSRIDParameter = cUSRID != null ?
                new ObjectParameter("CUSRID", cUSRID) :
                new ObjectParameter("CUSRID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_Company_OfficeMaster_Result>("pr_Search_Company_OfficeMaster", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, cUSRIDParameter);
        }
    
        public virtual ObjectResult<pr_Search_Company_Route_Master_Result> pr_Search_Company_Route_Master(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, string cUSRID)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var cUSRIDParameter = cUSRID != null ?
                new ObjectParameter("CUSRID", cUSRID) :
                new ObjectParameter("CUSRID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_Company_Route_Master_Result>("pr_Search_Company_Route_Master", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, cUSRIDParameter);
        }
    
        public virtual ObjectResult<pr_Search_Master_ChitGroup_Result> pr_Search_Master_ChitGroup(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, string cUSRID)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var cUSRIDParameter = cUSRID != null ?
                new ObjectParameter("CUSRID", cUSRID) :
                new ObjectParameter("CUSRID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_Master_ChitGroup_Result>("pr_Search_Master_ChitGroup", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, cUSRIDParameter);
        }
    
        public virtual ObjectResult<pr_Search_Master_ChitScheme_Result> pr_Search_Master_ChitScheme(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, string cUSRID)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var cUSRIDParameter = cUSRID != null ?
                new ObjectParameter("CUSRID", cUSRID) :
                new ObjectParameter("CUSRID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_Master_ChitScheme_Result>("pr_Search_Master_ChitScheme", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, cUSRIDParameter);
        }
    
        public virtual ObjectResult<pr_Search_Master_ClientMaster_Result> pr_Search_Master_ClientMaster(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, string cUSRID)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var cUSRIDParameter = cUSRID != null ?
                new ObjectParameter("CUSRID", cUSRID) :
                new ObjectParameter("CUSRID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_Master_ClientMaster_Result>("pr_Search_Master_ClientMaster", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, cUSRIDParameter);
        }
    
        public virtual ObjectResult<pr_Search_Master_ContactMaster_Result> pr_Search_Master_ContactMaster(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, string cUSRID)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var cUSRIDParameter = cUSRID != null ?
                new ObjectParameter("CUSRID", cUSRID) :
                new ObjectParameter("CUSRID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_Master_ContactMaster_Result>("pr_Search_Master_ContactMaster", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, cUSRIDParameter);
        }
    
        public virtual ObjectResult<pr_Search_Master_ContactTypeMaster_Result> pr_Search_Master_ContactTypeMaster(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_Master_ContactTypeMaster_Result>("pr_Search_Master_ContactTypeMaster", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount);
        }
    
        public virtual ObjectResult<pr_Search_Master_LoanScheme_Result> pr_Search_Master_LoanScheme(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, string cUSRID)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var cUSRIDParameter = cUSRID != null ?
                new ObjectParameter("CUSRID", cUSRID) :
                new ObjectParameter("CUSRID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_Master_LoanScheme_Result>("pr_Search_Master_LoanScheme", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, cUSRIDParameter);
        }
    
        public virtual ObjectResult<pr_Search_Masters_AmountCode_Result> pr_Search_Masters_AmountCode(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_Masters_AmountCode_Result>("pr_Search_Masters_AmountCode", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount);
        }
    
        public virtual ObjectResult<pr_Search_Masters_CompanyDetails_Result> pr_Search_Masters_CompanyDetails(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_Masters_CompanyDetails_Result>("pr_Search_Masters_CompanyDetails", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount);
        }
    
        public virtual ObjectResult<pr_Search_Masters_Department_Result> pr_Search_Masters_Department(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_Masters_Department_Result>("pr_Search_Masters_Department", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount);
        }
    
        public virtual ObjectResult<pr_Search_Masters_Designation_Result> pr_Search_Masters_Designation(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_Masters_Designation_Result>("pr_Search_Masters_Designation", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount);
        }
    
        public virtual ObjectResult<pr_Search_Masters_Employee_Result> pr_Search_Masters_Employee(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_Masters_Employee_Result>("pr_Search_Masters_Employee", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount);
        }
    
        public virtual ObjectResult<pr_Search_Masters_FundAccount_Result> pr_Search_Masters_FundAccount(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_Masters_FundAccount_Result>("pr_Search_Masters_FundAccount", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount);
        }
    
        public virtual ObjectResult<pr_Search_Masters_State_Result> pr_Search_Masters_State(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_Masters_State_Result>("pr_Search_Masters_State", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount);
        }
    
        public virtual ObjectResult<pr_Search_Transaction_Details_Result> pr_Search_Transaction_Details(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, string cUSRID)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var cUSRIDParameter = cUSRID != null ?
                new ObjectParameter("CUSRID", cUSRID) :
                new ObjectParameter("CUSRID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_Transaction_Details_Result>("pr_Search_Transaction_Details", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, cUSRIDParameter);
        }
    
        public virtual ObjectResult<pr_search_type_master_Result1> pr_search_type_master(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_search_type_master_Result1>("pr_search_type_master", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount);
        }
    
        public virtual ObjectResult<pr_Search_Master_CityMaster_Result> pr_Search_Master_CityMaster(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, string cUSRID)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var cUSRIDParameter = cUSRID != null ?
                new ObjectParameter("CUSRID", cUSRID) :
                new ObjectParameter("CUSRID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_Master_CityMaster_Result>("pr_Search_Master_CityMaster", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, cUSRIDParameter);
        }
    
        public virtual ObjectResult<pr_Search_Master_LocalityMaster_Result> pr_Search_Master_LocalityMaster(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, string cUSRID)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var cUSRIDParameter = cUSRID != null ?
                new ObjectParameter("CUSRID", cUSRID) :
                new ObjectParameter("CUSRID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_Master_LocalityMaster_Result>("pr_Search_Master_LocalityMaster", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, cUSRIDParameter);
        }
    
        public virtual ObjectResult<pr_Get_QRCode_Chit_Subscription_Dtl_Result> pr_Get_QRCode_Chit_Subscription_Dtl(string usrid, Nullable<int> empid, Nullable<int> subsid)
        {
            var usridParameter = usrid != null ?
                new ObjectParameter("usrid", usrid) :
                new ObjectParameter("usrid", typeof(string));
    
            var empidParameter = empid.HasValue ?
                new ObjectParameter("empid", empid) :
                new ObjectParameter("empid", typeof(int));
    
            var subsidParameter = subsid.HasValue ?
                new ObjectParameter("subsid", subsid) :
                new ObjectParameter("subsid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Get_QRCode_Chit_Subscription_Dtl_Result>("pr_Get_QRCode_Chit_Subscription_Dtl", usridParameter, empidParameter, subsidParameter);
        }
    
        public virtual ObjectResult<pr_Get_Chit_Collection_Pattern_n_Actuals_Details_Result> pr_Get_Chit_Collection_Pattern_n_Actuals_Details(Nullable<int> chitSubsID, string usrid)
        {
            var chitSubsIDParameter = chitSubsID.HasValue ?
                new ObjectParameter("ChitSubsID", chitSubsID) :
                new ObjectParameter("ChitSubsID", typeof(int));
    
            var usridParameter = usrid != null ?
                new ObjectParameter("usrid", usrid) :
                new ObjectParameter("usrid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Get_Chit_Collection_Pattern_n_Actuals_Details_Result>("pr_Get_Chit_Collection_Pattern_n_Actuals_Details", chitSubsIDParameter, usridParameter);
        }
    
        public virtual ObjectResult<pr_Get_Book_List_Result> pr_Get_Book_List(Nullable<int> prodtype, Nullable<int> subsid)
        {
            var prodtypeParameter = prodtype.HasValue ?
                new ObjectParameter("prodtype", prodtype) :
                new ObjectParameter("prodtype", typeof(int));
    
            var subsidParameter = subsid.HasValue ?
                new ObjectParameter("subsid", subsid) :
                new ObjectParameter("subsid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Get_Book_List_Result>("pr_Get_Book_List", prodtypeParameter, subsidParameter);
        }
    
        public virtual ObjectResult<pr_Get_ChitGroup_MemberDtl_Result> pr_Get_ChitGroup_MemberDtl(Nullable<int> chitGrpid)
        {
            var chitGrpidParameter = chitGrpid.HasValue ?
                new ObjectParameter("ChitGrpid", chitGrpid) :
                new ObjectParameter("ChitGrpid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Get_ChitGroup_MemberDtl_Result>("pr_Get_ChitGroup_MemberDtl", chitGrpidParameter);
        }
    
        public virtual ObjectResult<pr_Get_Chit_Dividend_Schedule_n_Actuals_Details_Result> pr_Get_Chit_Dividend_Schedule_n_Actuals_Details(Nullable<int> chitSubsID, string usrid)
        {
            var chitSubsIDParameter = chitSubsID.HasValue ?
                new ObjectParameter("ChitSubsID", chitSubsID) :
                new ObjectParameter("ChitSubsID", typeof(int));
    
            var usridParameter = usrid != null ?
                new ObjectParameter("usrid", usrid) :
                new ObjectParameter("usrid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Get_Chit_Dividend_Schedule_n_Actuals_Details_Result>("pr_Get_Chit_Dividend_Schedule_n_Actuals_Details", chitSubsIDParameter, usridParameter);
        }
    
        public virtual ObjectResult<pr_Search_Transaction_Collection_Details_Result> pr_Search_Transaction_Collection_Details(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, string cUSRID, Nullable<int> empID, Nullable<int> prodType, Nullable<int> routeID, Nullable<System.DateTime> frDt, Nullable<System.DateTime> toDt)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var cUSRIDParameter = cUSRID != null ?
                new ObjectParameter("CUSRID", cUSRID) :
                new ObjectParameter("CUSRID", typeof(string));
    
            var empIDParameter = empID.HasValue ?
                new ObjectParameter("empID", empID) :
                new ObjectParameter("empID", typeof(int));
    
            var prodTypeParameter = prodType.HasValue ?
                new ObjectParameter("ProdType", prodType) :
                new ObjectParameter("ProdType", typeof(int));
    
            var routeIDParameter = routeID.HasValue ?
                new ObjectParameter("RouteID", routeID) :
                new ObjectParameter("RouteID", typeof(int));
    
            var frDtParameter = frDt.HasValue ?
                new ObjectParameter("FrDt", frDt) :
                new ObjectParameter("FrDt", typeof(System.DateTime));
    
            var toDtParameter = toDt.HasValue ?
                new ObjectParameter("ToDt", toDt) :
                new ObjectParameter("ToDt", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_Transaction_Collection_Details_Result>("pr_Search_Transaction_Collection_Details", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, cUSRIDParameter, empIDParameter, prodTypeParameter, routeIDParameter, frDtParameter, toDtParameter);
        }
    
        public virtual ObjectResult<pr_Search_Transaction_Payment_Details_Result> pr_Search_Transaction_Payment_Details(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, string cUSRID, Nullable<int> empID, Nullable<int> prodType, Nullable<System.DateTime> frDt, Nullable<System.DateTime> toDt)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var cUSRIDParameter = cUSRID != null ?
                new ObjectParameter("CUSRID", cUSRID) :
                new ObjectParameter("CUSRID", typeof(string));
    
            var empIDParameter = empID.HasValue ?
                new ObjectParameter("empID", empID) :
                new ObjectParameter("empID", typeof(int));
    
            var prodTypeParameter = prodType.HasValue ?
                new ObjectParameter("ProdType", prodType) :
                new ObjectParameter("ProdType", typeof(int));
    
            var frDtParameter = frDt.HasValue ?
                new ObjectParameter("FrDt", frDt) :
                new ObjectParameter("FrDt", typeof(System.DateTime));
    
            var toDtParameter = toDt.HasValue ?
                new ObjectParameter("ToDt", toDt) :
                new ObjectParameter("ToDt", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_Transaction_Payment_Details_Result>("pr_Search_Transaction_Payment_Details", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, cUSRIDParameter, empIDParameter, prodTypeParameter, frDtParameter, toDtParameter);
        }
    
        public virtual ObjectResult<pr_Search_Product_ChitSubcription_Result> pr_Search_Product_ChitSubcription(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, string cUSRID, Nullable<System.DateTime> frDt, Nullable<System.DateTime> toDt, Nullable<int> colAgnt, Nullable<int> custtype)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var cUSRIDParameter = cUSRID != null ?
                new ObjectParameter("CUSRID", cUSRID) :
                new ObjectParameter("CUSRID", typeof(string));
    
            var frDtParameter = frDt.HasValue ?
                new ObjectParameter("FrDt", frDt) :
                new ObjectParameter("FrDt", typeof(System.DateTime));
    
            var toDtParameter = toDt.HasValue ?
                new ObjectParameter("ToDt", toDt) :
                new ObjectParameter("ToDt", typeof(System.DateTime));
    
            var colAgntParameter = colAgnt.HasValue ?
                new ObjectParameter("ColAgnt", colAgnt) :
                new ObjectParameter("ColAgnt", typeof(int));
    
            var custtypeParameter = custtype.HasValue ?
                new ObjectParameter("custtype", custtype) :
                new ObjectParameter("custtype", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_Product_ChitSubcription_Result>("pr_Search_Product_ChitSubcription", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, cUSRIDParameter, frDtParameter, toDtParameter, colAgntParameter, custtypeParameter);
        }
    
        public virtual ObjectResult<pr_Search_Payment_Result> pr_Search_Payment(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, Nullable<System.DateTime> pSDate, Nullable<System.DateTime> pEDate, Nullable<int> pCompyid, string cUsrid, Nullable<int> pOfficeID)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var pSDateParameter = pSDate.HasValue ?
                new ObjectParameter("PSDate", pSDate) :
                new ObjectParameter("PSDate", typeof(System.DateTime));
    
            var pEDateParameter = pEDate.HasValue ?
                new ObjectParameter("PEDate", pEDate) :
                new ObjectParameter("PEDate", typeof(System.DateTime));
    
            var pCompyidParameter = pCompyid.HasValue ?
                new ObjectParameter("PCompyid", pCompyid) :
                new ObjectParameter("PCompyid", typeof(int));
    
            var cUsridParameter = cUsrid != null ?
                new ObjectParameter("CUsrid", cUsrid) :
                new ObjectParameter("CUsrid", typeof(string));
    
            var pOfficeIDParameter = pOfficeID.HasValue ?
                new ObjectParameter("POfficeID", pOfficeID) :
                new ObjectParameter("POfficeID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_Payment_Result>("pr_Search_Payment", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, pSDateParameter, pEDateParameter, pCompyidParameter, cUsridParameter, pOfficeIDParameter);
        }
    
        public virtual ObjectResult<pr_Search_ReceiptDetail_Result> pr_Search_ReceiptDetail(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, Nullable<System.DateTime> pSDate, Nullable<System.DateTime> pEDate, Nullable<int> pCompyid, string cUsrid, Nullable<int> pOfficeID)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var pSDateParameter = pSDate.HasValue ?
                new ObjectParameter("PSDate", pSDate) :
                new ObjectParameter("PSDate", typeof(System.DateTime));
    
            var pEDateParameter = pEDate.HasValue ?
                new ObjectParameter("PEDate", pEDate) :
                new ObjectParameter("PEDate", typeof(System.DateTime));
    
            var pCompyidParameter = pCompyid.HasValue ?
                new ObjectParameter("PCompyid", pCompyid) :
                new ObjectParameter("PCompyid", typeof(int));
    
            var cUsridParameter = cUsrid != null ?
                new ObjectParameter("CUsrid", cUsrid) :
                new ObjectParameter("CUsrid", typeof(string));
    
            var pOfficeIDParameter = pOfficeID.HasValue ?
                new ObjectParameter("POfficeID", pOfficeID) :
                new ObjectParameter("POfficeID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_ReceiptDetail_Result>("pr_Search_ReceiptDetail", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, pSDateParameter, pEDateParameter, pCompyidParameter, cUsridParameter, pOfficeIDParameter);
        }
    
        public virtual ObjectResult<pr_Search_Transaction_BookVerification_Details_Result> pr_Search_Transaction_BookVerification_Details(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, string cUSRID, Nullable<int> empID, Nullable<int> prodType, Nullable<System.DateTime> frDt, Nullable<System.DateTime> toDt, Nullable<int> routeID, Nullable<int> collectionagent, Nullable<int> bookVerifiedBy)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var cUSRIDParameter = cUSRID != null ?
                new ObjectParameter("CUSRID", cUSRID) :
                new ObjectParameter("CUSRID", typeof(string));
    
            var empIDParameter = empID.HasValue ?
                new ObjectParameter("empID", empID) :
                new ObjectParameter("empID", typeof(int));
    
            var prodTypeParameter = prodType.HasValue ?
                new ObjectParameter("ProdType", prodType) :
                new ObjectParameter("ProdType", typeof(int));
    
            var frDtParameter = frDt.HasValue ?
                new ObjectParameter("FrDt", frDt) :
                new ObjectParameter("FrDt", typeof(System.DateTime));
    
            var toDtParameter = toDt.HasValue ?
                new ObjectParameter("ToDt", toDt) :
                new ObjectParameter("ToDt", typeof(System.DateTime));
    
            var routeIDParameter = routeID.HasValue ?
                new ObjectParameter("RouteID", routeID) :
                new ObjectParameter("RouteID", typeof(int));
    
            var collectionagentParameter = collectionagent.HasValue ?
                new ObjectParameter("collectionagent", collectionagent) :
                new ObjectParameter("collectionagent", typeof(int));
    
            var bookVerifiedByParameter = bookVerifiedBy.HasValue ?
                new ObjectParameter("BookVerifiedBy", bookVerifiedBy) :
                new ObjectParameter("BookVerifiedBy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_Transaction_BookVerification_Details_Result>("pr_Search_Transaction_BookVerification_Details", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, cUSRIDParameter, empIDParameter, prodTypeParameter, frDtParameter, toDtParameter, routeIDParameter, collectionagentParameter, bookVerifiedByParameter);
        }
    
        public virtual ObjectResult<pr_SearchAccountGroup_Result> pr_SearchAccountGroup(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_SearchAccountGroup_Result>("pr_SearchAccountGroup", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount);
        }
    
        public virtual ObjectResult<pr_SearchAccountHeadMaster_Result> pr_SearchAccountHeadMaster(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_SearchAccountHeadMaster_Result>("pr_SearchAccountHeadMaster", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount);
        }
    
        public virtual ObjectResult<pr_Roles_Wise_Customer_Name_Assgn_Result> pr_Roles_Wise_Customer_Name_Assgn(string cUSRID, Nullable<int> pEmplId)
        {
            var cUSRIDParameter = cUSRID != null ?
                new ObjectParameter("CUSRID", cUSRID) :
                new ObjectParameter("CUSRID", typeof(string));
    
            var pEmplIdParameter = pEmplId.HasValue ?
                new ObjectParameter("PEmplId", pEmplId) :
                new ObjectParameter("PEmplId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Roles_Wise_Customer_Name_Assgn_Result>("pr_Roles_Wise_Customer_Name_Assgn", cUSRIDParameter, pEmplIdParameter);
        }
    
        public virtual ObjectResult<pr_Get_Book_Verification_Entry_Details_Result> pr_Get_Book_Verification_Entry_Details(Nullable<int> bkvfcnlstid)
        {
            var bkvfcnlstidParameter = bkvfcnlstid.HasValue ?
                new ObjectParameter("bkvfcnlstid", bkvfcnlstid) :
                new ObjectParameter("bkvfcnlstid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Get_Book_Verification_Entry_Details_Result>("pr_Get_Book_Verification_Entry_Details", bkvfcnlstidParameter);
        }
    
        public virtual ObjectResult<pr_Get_Master_Types_Result> pr_Get_Master_Types(string categorydesc, string classification)
        {
            var categorydescParameter = categorydesc != null ?
                new ObjectParameter("categorydesc", categorydesc) :
                new ObjectParameter("categorydesc", typeof(string));
    
            var classificationParameter = classification != null ?
                new ObjectParameter("classification", classification) :
                new ObjectParameter("classification", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Get_Master_Types_Result>("pr_Get_Master_Types", categorydescParameter, classificationParameter);
        }
    
        public virtual ObjectResult<pr_Search_Product_LoanSubscription_Result> pr_Search_Product_LoanSubscription(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, string cUSRID, Nullable<System.DateTime> frDt, Nullable<System.DateTime> toDt)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var cUSRIDParameter = cUSRID != null ?
                new ObjectParameter("CUSRID", cUSRID) :
                new ObjectParameter("CUSRID", typeof(string));
    
            var frDtParameter = frDt.HasValue ?
                new ObjectParameter("FrDt", frDt) :
                new ObjectParameter("FrDt", typeof(System.DateTime));
    
            var toDtParameter = toDt.HasValue ?
                new ObjectParameter("ToDt", toDt) :
                new ObjectParameter("ToDt", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_Product_LoanSubscription_Result>("pr_Search_Product_LoanSubscription", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, cUSRIDParameter, frDtParameter, toDtParameter);
        }
    }
}
