//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHITERP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_CUSTOMER_LOCATION_CBX_ASSGN
    {
        public string LOCTDESC { get; set; }
        public int CATEID { get; set; }
        public int CATEAID { get; set; }
        public int LOCTID { get; set; }
    }
}
