USE [FinFusion]
GO

/****** Object:  Table [dbo].[ClientMaster]    Script Date: 19-06-2022 09:14:27 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
drop table [ClientMaster]
go

CREATE TABLE [dbo].[ClientMaster](
	[CLIENTID] [int] IDENTITY(1,1) NOT NULL,
	[CLIENTTID] [int] NOT NULL,
	[CLIENTNAME] [varchar](250) NULL,	
	[DATEOFBIRTH] [datetime] NULL,
	[GENDERTYPEID] [int] NULL,
	[CLIENTMOBILENO1] [varchar](25) NULL,
	[CLIENTMOBILENO2] [varchar](25) NULL,
	[CLIENTLANDLINENO1] [varchar](25) NULL,
	[CLIENTLANDLINENO2] [varchar](25) NULL,
	[CLIENTEMAILID] [varchar](150) NULL,
	[CLIENTCONTACTPERSON] [varchar](150) NULL,
	[CLIENTCONTACTDESIGNATION] [varchar](150) NULL,	
	[CLIENTADDRESS1] [varchar](150) NULL,
	[CLIENTADDRESS2] [varchar](150) NULL,
	[CLIENTCITY] [varchar](150) NULL,
	[CLIENTSTATEID] [int] NULL,
	[CLIENTCOUNTRYID] [int] NOT NULL,
	[CLIENTPINCD] [varchar](150) NULL,
	[DISPSTATUS] [smallint] NULL,
	[CreatedBy] [varchar](50) NULL,
	[CreatedDt] [datetime] NULL,
	[UpdatedBy] [varchar](50) NULL,
	[UpdatedDt] [datetime] NULL,
	[REFCLIENTID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[CLIENTID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ClientMaster] ADD  DEFAULT ((0)) FOR [CLIENTTID]
GO

ALTER TABLE [dbo].[ClientMaster] ADD  DEFAULT ('') FOR [CLIENTNAME]
GO

ALTER TABLE [dbo].[ClientMaster] ADD  DEFAULT ('') FOR [CLIENTCONTACTPERSON]
GO

ALTER TABLE [dbo].[ClientMaster] ADD  DEFAULT ('') FOR [DATEOFBIRTH]
GO

ALTER TABLE [dbo].[ClientMaster] ADD  DEFAULT ((0)) FOR [GENDERTYPEID]
GO

ALTER TABLE [dbo].[ClientMaster] ADD  DEFAULT ('') FOR [CLIENTMOBILENO1]
GO

ALTER TABLE [dbo].[ClientMaster] ADD  DEFAULT ('') FOR [CLIENTMOBILENO2]
GO

ALTER TABLE [dbo].[ClientMaster] ADD  DEFAULT ('') FOR [CLIENTLANDLINENO1]
GO

ALTER TABLE [dbo].[ClientMaster] ADD  DEFAULT ('') FOR [CLIENTLANDLINENO2]
GO

ALTER TABLE [dbo].[ClientMaster] ADD  DEFAULT ('') FOR [CLIENTEMAILID]
GO

ALTER TABLE [dbo].[ClientMaster] ADD  DEFAULT ('') FOR [CLIENTCONTACTDESIGNATION]
GO


ALTER TABLE [dbo].[ClientMaster] ADD  DEFAULT ('') FOR [CLIENTADDRESS1]
GO

ALTER TABLE [dbo].[ClientMaster] ADD  DEFAULT ('') FOR [CLIENTADDRESS2]
GO

ALTER TABLE [dbo].[ClientMaster] ADD  DEFAULT ('') FOR [CLIENTCITY]
GO

ALTER TABLE [dbo].[ClientMaster] ADD  DEFAULT ((0)) FOR [CLIENTSTATEID]
GO

ALTER TABLE [dbo].[ClientMaster] ADD  DEFAULT ((0)) FOR [CLIENTCOUNTRYID]
GO

ALTER TABLE [dbo].[ClientMaster] ADD  DEFAULT ('') FOR [CLIENTPINCD]
GO

ALTER TABLE [dbo].[ClientMaster] ADD  DEFAULT ((0)) FOR [DISPSTATUS]
GO


