USE [MCT_ERP]
GO

/****** Object:  Table [dbo].[CATEGORYMASTER]    Script Date: 23/02/2022 16:38:34 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CATEGORYMASTER](
    [CATEID] [int] IDENTITY(1,1) NOT NULL,	
	[CATETID] [int] NOT NULL CONSTRAINT [DF_CATEGORYMASTER_CATETID]  DEFAULT ((0)),
	[CATENAME] [varchar](100) NOT NULL CONSTRAINT [DF_CATEGORYMASTER_CATENAME]  DEFAULT (NULL),
	[CATEDNAME] [varchar](100) NULL,
	[CATEADDR] [varchar](250) NULL,
	[CATEPHNID] [varchar](4) NOT NULL,
	[CATEPHN1] [varchar](15) NULL,
	[CATEPHN2] [varchar](15) NULL,
	[CATEPHN3] [varchar](15) NULL,
	[CATEPHN4] [varchar](15) NULL,
	[CATEMAIL] [varchar](100) NULL,
	[CATECPRSN] [varchar](100) NULL,
	[CATECODE] [varchar](15) NULL,
	[CUSRID] [varchar](100) NULL CONSTRAINT [DF_CATEGORYMASTER_CUSRID]  DEFAULT (('')),
	[LMUSRID] [varchar](100) NULL CONSTRAINT [DF_CATEGORYMASTER_LMUSRID]  DEFAULT (('')),
	[ACHEADID] [int] NULL CONSTRAINT [DF_CATEGORYMASTER_ACHEADID]  DEFAULT ((0)),
	[TARIFFMID] [int] NULL CONSTRAINT [DF_CATEGORYMASTER_TARIFFMID]  DEFAULT ((0)),
	[DISPSTATUS] [smallint] NULL CONSTRAINT [DF_CATEGORYMASTER_DISPSTATUS]  DEFAULT ((0)),
	[PRCSDATE] [datetime] NULL CONSTRAINT [DF_CATEGORYMASTER_PRCSDATE]  DEFAULT (NULL),
	[CATEBTYPE] [smallint] NULL CONSTRAINT [DF_CATEGORYMASTER_CATEBTYPE]  DEFAULT ((0)),
	[CATEGSTNO] [varchar](15) NULL CONSTRAINT [DF_CATEGORYMASTER_CATEGSTNO]  DEFAULT (NULL),
	[CATEADDR1] [varchar](1000) NULL CONSTRAINT [DF_CATEGORYMASTER_CATEADDR1]  DEFAULT (NULL),
	[CATEADDR2] [varchar](1000) NULL CONSTRAINT [DF_CATEGORYMASTER_CATEADDR2]  DEFAULT (NULL),
	[CATEADDR3] [varchar](1000) NULL CONSTRAINT [DF_CATEGORYMASTER_CATEADDR3]  DEFAULT (NULL),
	[CATEADDR4] [varchar](1000) NULL CONSTRAINT [DF_CATEGORYMASTER_CATEADDR4]  DEFAULT (NULL),
	[CATELICNO] [varchar](100) NULL CONSTRAINT [DF_CATEGORYMASTER_CATELICNO]  DEFAULT (NULL),
	[CATETDSEXPRN] [numeric](18, 2) NULL CONSTRAINT [DF_CATEGORYMASTER_CATETDSEXPRN]  DEFAULT ((0)),
	[CATEACODE] [varchar](15) NULL CONSTRAINT [DF_CATEGORYMASTER_CATEACODE]  DEFAULT (NULL),
	[CATELTYPE] [smallint] NOT NULL CONSTRAINT [DF_CATEGORYMASTER_CATELTYPE]  DEFAULT ((0)),

 CONSTRAINT [PK_CATEGORYMASTER] PRIMARY KEY CLUSTERED 
(
	[CATEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO



