USE [MCT_ERP]
GO

/****** Object:  Table [dbo].[CATEGORY_ADDRESS_DETAIL]    Script Date: 23/02/2022 10:29:20 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CATEGORY_ADDRESS_DETAIL](
	[CATEAID] [int] IDENTITY(1,1) NOT NULL,
	[CATEID] [int] NOT NULL,
	[STATEID] [int] NOT NULL,
	[CATEAGSTNO] [varchar](50) NULL,
	[CATEAADDR1] [varchar](100) NULL,
	[CATEAADDR2] [varchar](100) NULL,
	[CATEAADDR3] [varchar](100) NULL,
	[CATEAADDR4] [varchar](100) NULL,
	[CATEATYPEDESC] [varchar](50) NULL,
	[CATEAPANNO] [varchar](100) NOT NULL CONSTRAINT [DF_CATEGORY_ADDRESS_DETAIL_CATEBNAME16]  DEFAULT (''),
PRIMARY KEY CLUSTERED 
(
	[CATEAID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


