USE [MCT_ERP]
GO

/****** Object:  Table [dbo].[CATEGORYTYPEMASTER]    Script Date: 23/02/2022 10:31:03 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CATEGORYTYPEMASTER](
	[CATETID] [int] IDENTITY(1,1) NOT NULL,
	[CATETDESC] [varchar](50) NOT NULL CONSTRAINT [DF_CATEGORYTYPEMASTER_CATETDESC]  DEFAULT (''),
	[CATETCODE] [varchar](15) NOT NULL CONSTRAINT [DF_CATEGORYTYPEMASTER_CATETCODE]  DEFAULT (''),
	[CUSRID] [varchar](100) NULL CONSTRAINT [DF_CATEGORYTYPEMASTER_CUSRID]  DEFAULT (''),
	[LMUSRID] [varchar](100) NULL CONSTRAINT [DF_CATEGORYTYPEMASTER_LMUSRID]  DEFAULT (('')),
	[DISPSTATUS] [smallint] NULL,
	[PRCSDATE] [datetime] NULL CONSTRAINT [DF_CATEGORYTYPEMASTER_PRCSDATE]  DEFAULT (NULL),
 CONSTRAINT [PK_CATEGORYTYPEMASTER] PRIMARY KEY CLUSTERED 
(
	[CATETID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


