USE [MCT_ERP]
GO

/****** Object:  Table [dbo].[DEPARTMENTMASTER]    Script Date: 23/02/2022 10:37:39 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[DEPARTMENTMASTER](
	[DEPTID] [int] IDENTITY(1,1) NOT NULL,
	[DEPTDESC] [varchar](100) NULL CONSTRAINT [DF_DEPARTMENTMASTER_DEPTDESC]  DEFAULT (NULL),
	[DEPTCODE] [varchar](15) NULL CONSTRAINT [DF_DEPARTMENTMASTER_DEPTCODE]  DEFAULT (NULL),
	[CUSRID] [varchar](100) NULL,
	[LMUSRID] [varchar](100) NULL CONSTRAINT [DF_DEPARTMENTMASTER_LMUSRID]  DEFAULT (('')),
	[DISPSTATUS] [smallint] NULL CONSTRAINT [DF_DEPARTMENTMASTER_DISPSTATUS]  DEFAULT ((0)),
	[PRCSDATE] [datetime] NULL CONSTRAINT [DF_DEPARTMENTMASTER_PRCSDATE]  DEFAULT (NULL),
 CONSTRAINT [PK_DEPARTMENTMASTER] PRIMARY KEY CLUSTERED 
(
	[DEPTID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


