USE [MCT_ERP]
GO

/****** Object:  Table [dbo].[EMPLOYEEYARDMAPPINGDETAIL]    Script Date: 25/02/2022 14:59:09 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[EMPLOYEEYARDMAPPINGDETAIL](
	[EYMDID] [int] IDENTITY(1,1) NOT NULL,
	[YRDID] [int] NOT NULL,
	[COMPID] [int] NOT NULL,
	[EMPID] [int] NOT NULL,
	[EFFFRMDT] [datetime] NULL,
	[EFFTODT] [datetime] NULL,
	[DISPSTATUS] [smallint] NULL,
	[CreatedBy] [varchar](50) NULL,
	[CreatedDt] [datetime] NULL,
	[UpdatedBy] [varchar](50) NULL,
	[UpdatedDt] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[EYMDID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[EMPLOYEEYARDMAPPINGDETAIL] ADD  DEFAULT ((0)) FOR [YRDID]
GO

ALTER TABLE [dbo].[EMPLOYEEYARDMAPPINGDETAIL] ADD  DEFAULT ((0)) FOR [COMPID]
GO

ALTER TABLE [dbo].[EMPLOYEEYARDMAPPINGDETAIL] ADD  DEFAULT ((0)) FOR [EMPID]
GO

ALTER TABLE [dbo].[EMPLOYEEYARDMAPPINGDETAIL] ADD  DEFAULT ((0)) FOR [DISPSTATUS]
GO


