USE [MCT_ERP]
GO

/****** Object:  Table [dbo].[EMPLOYEEMASTER]    Script Date: 23/02/2022 10:37:18 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[EMPLOYEEMASTER](
	[CATEID] [int] IDENTITY(1,1) NOT NULL,
	[CATETID] [int] NOT NULL CONSTRAINT [DF_EMPLOYEEMASTER_CATETID]  DEFAULT ((0)),
	[CATENAME] [varchar](100) NOT NULL CONSTRAINT [DF_EMPLOYEEMASTER_CATENAME]  DEFAULT (NULL),
	[CATEADDR1] [varchar](100) NULL CONSTRAINT [DF_EMPLOYEEMASTER_CATEADDR1]  DEFAULT (NULL),
	[CATEADDR2] [varchar](100) NULL CONSTRAINT [DF_EMPLOYEEMASTER_CATEADDR2]  DEFAULT (NULL),
	[CATEADDR3] [varchar](100) NULL CONSTRAINT [DF_EMPLOYEEMASTER_CATEADDR3]  DEFAULT (NULL),
	[CATEADDR4] [varchar](100) NULL CONSTRAINT [DF_EMPLOYEEMASTER_CATEADDR4]  DEFAULT (NULL),
	[CATEPHN1] [varchar](25) NULL CONSTRAINT [DF_EMPLOYEEMASTER_CATEPHN1]  DEFAULT (NULL),
	[CATEPHN2] [varchar](25) NULL CONSTRAINT [DF_EMPLOYEEMASTER_CATEPHN2]  DEFAULT (NULL),
	[CATEPHN3] [varchar](25) NULL CONSTRAINT [DF_EMPLOYEEMASTER_CATEPHN3]  DEFAULT (NULL),
	[CATEPHN4] [varchar](25) NULL CONSTRAINT [DF_EMPLOYEEMASTER_CATEPHN4]  DEFAULT (NULL),
	[CATECPNAME] [varchar](100) NULL CONSTRAINT [DF_EMPLOYEEMASTER_CATECPNAME]  DEFAULT (NULL),
	[CATEEMAIL] [varchar](100) NULL CONSTRAINT [DF_EMPLOYEEMASTER_CATEEMAIL]  DEFAULT (NULL),
	[DEPTID] [int] NOT NULL CONSTRAINT [DF_EMPLOYEEMASTER_DEPTID]  DEFAULT ((0)),
	[DSGNID] [int] NOT NULL CONSTRAINT [DF_EMPLOYEEMASTER_DSGNID]  DEFAULT ((0)),
	[LOCTID] [int] NULL CONSTRAINT [DF_EMPLOYEEMASTER_LOCTID]  DEFAULT ((0)),
	[CATEDOB] [smalldatetime] NULL CONSTRAINT [DF_EMPLOYEEMASTER_CATEDOB]  DEFAULT (NULL),
	[CATEDOJ] [smalldatetime] NULL CONSTRAINT [DF_EMPLOYEEMASTER_CATEDOJ]  DEFAULT (NULL),
	[CATEDOC] [smalldatetime] NULL CONSTRAINT [DF_EMPLOYEEMASTER_CATEDOC]  DEFAULT (NULL),
	[CATEDOR] [smalldatetime] NULL CONSTRAINT [DF_EMPLOYEEMASTER_CATEDOR]  DEFAULT (NULL),
	[CATESTATUS] [smallint] NOT NULL CONSTRAINT [DF_EMPLOYEEMASTER_CATESTATUS]  DEFAULT ((0)),
	[CATECODE] [varchar](15) NOT NULL CONSTRAINT [DF_EMPLOYEEMASTER_CATECODE]  DEFAULT (NULL),
	[CUSRID] [varchar](100) NOT NULL,
	[LMUSRID] [varchar](100) NULL CONSTRAINT [DF_EMPLOYEEMASTER_LMUSRID]  DEFAULT (('')),
	[DISPSTATUS] [smallint] NOT NULL CONSTRAINT [DF_EMPLOYEEMASTER_DISPSTATUS]  DEFAULT ((0)),
	[PRCSDATE] [datetime] NOT NULL CONSTRAINT [DF_EMPLOYEEMASTER_PRCSDATE]  DEFAULT (NULL),
	[REGNID] [int] NOT NULL CONSTRAINT [DF_EMPLOYEEMASTER_REGNID]  DEFAULT ((0)),
 CONSTRAINT [PK_EMPLOYEEMASTER] PRIMARY KEY CLUSTERED 
(
	[CATEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


