USE [MCT_ERP]
GO

/****** Object:  Table [dbo].[EMPLOYEEMASTER]    Script Date: 09-02-2022 19:18:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[EMPLOYEEMASTER](
	[CATEID] [int] IDENTITY(1,1) NOT NULL,
	[CATETID] [int] NOT NULL,
	[CATENAME] [varchar](100) NOT NULL,
	[CATEADDR1] [varchar](100) NULL,
	[CATEADDR2] [varchar](100) NULL,
	[CATEADDR3] [varchar](100) NULL,
	[CATEADDR4] [varchar](100) NULL,
	[CATEPHN1] [varchar](25) NULL,
	[CATEPHN2] [varchar](25) NULL,
	[CATEPHN3] [varchar](25) NULL,
	[CATEPHN4] [varchar](25) NULL,
	[CATECPNAME] [varchar](100) NULL,
	[CATEEMAIL] [varchar](100) NULL,
	[DEPTID] [int] NOT NULL,
	[DSGNID] [int] NOT NULL,
	[LOCTID] [int] NULL,
	[CATEDOB] [smalldatetime] NULL,
	[CATEDOJ] [smalldatetime] NULL,
	[CATEDOC] [smalldatetime] NULL,
	[CATEDOR] [smalldatetime] NULL,
	[CATESTATUS] [smallint] NOT NULL,
	[CATECODE] [varchar](15) NOT NULL,
	[CUSRID] [varchar](100) NOT NULL,
	[LMUSRID] [int] NOT NULL,
	[DISPSTATUS] [smallint] NOT NULL,
	[PRCSDATE] [datetime] NOT NULL,
	[REGNID] [int] NOT NULL,
 CONSTRAINT [PK_EMPLOYEEMASTER] PRIMARY KEY CLUSTERED 
(
	[CATEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[EMPLOYEEMASTER] ADD  CONSTRAINT [DF_EMPLOYEEMASTER_CATETID]  DEFAULT ((0)) FOR [CATETID]
GO

ALTER TABLE [dbo].[EMPLOYEEMASTER] ADD  CONSTRAINT [DF_EMPLOYEEMASTER_CATENAME]  DEFAULT (NULL) FOR [CATENAME]
GO

ALTER TABLE [dbo].[EMPLOYEEMASTER] ADD  CONSTRAINT [DF_Table_1_CATEADDR]  DEFAULT (NULL) FOR [CATEADDR1]
GO

ALTER TABLE [dbo].[EMPLOYEEMASTER] ADD  CONSTRAINT [DF_Table_1_CATEADDR13]  DEFAULT (NULL) FOR [CATEADDR2]
GO

ALTER TABLE [dbo].[EMPLOYEEMASTER] ADD  CONSTRAINT [DF_Table_1_CATEADDR12]  DEFAULT (NULL) FOR [CATEADDR3]
GO

ALTER TABLE [dbo].[EMPLOYEEMASTER] ADD  CONSTRAINT [DF_Table_1_CATEADDR11]  DEFAULT (NULL) FOR [CATEADDR4]
GO

ALTER TABLE [dbo].[EMPLOYEEMASTER] ADD  CONSTRAINT [DF_EMPLOYEEMASTER_CATEPHN1]  DEFAULT (NULL) FOR [CATEPHN1]
GO

ALTER TABLE [dbo].[EMPLOYEEMASTER] ADD  CONSTRAINT [DF_EMPLOYEEMASTER_CATEPHN2]  DEFAULT (NULL) FOR [CATEPHN2]
GO

ALTER TABLE [dbo].[EMPLOYEEMASTER] ADD  CONSTRAINT [DF_Table_1_CATEPHN22]  DEFAULT (NULL) FOR [CATEPHN3]
GO

ALTER TABLE [dbo].[EMPLOYEEMASTER] ADD  CONSTRAINT [DF_Table_1_CATEPHN21]  DEFAULT (NULL) FOR [CATEPHN4]
GO

ALTER TABLE [dbo].[EMPLOYEEMASTER] ADD  CONSTRAINT [DF_Table_1_CATEPHN41]  DEFAULT (NULL) FOR [CATECPNAME]
GO

ALTER TABLE [dbo].[EMPLOYEEMASTER] ADD  CONSTRAINT [DF_Table_1_CATECPNAME1]  DEFAULT (NULL) FOR [CATEEMAIL]
GO

ALTER TABLE [dbo].[EMPLOYEEMASTER] ADD  CONSTRAINT [DF_EMPLOYEEMASTER_DEPTID]  DEFAULT ((0)) FOR [DEPTID]
GO

ALTER TABLE [dbo].[EMPLOYEEMASTER] ADD  CONSTRAINT [DF_EMPLOYEEMASTER_DSGNID]  DEFAULT ((0)) FOR [DSGNID]
GO

ALTER TABLE [dbo].[EMPLOYEEMASTER] ADD  CONSTRAINT [DF_EMPLOYEEMASTER_LOCTID]  DEFAULT ((0)) FOR [LOCTID]
GO

ALTER TABLE [dbo].[EMPLOYEEMASTER] ADD  CONSTRAINT [DF_EMPLOYEEMASTER_CATEDOB]  DEFAULT (NULL) FOR [CATEDOB]
GO

ALTER TABLE [dbo].[EMPLOYEEMASTER] ADD  CONSTRAINT [DF_EMPLOYEEMASTER_CATEDOJ]  DEFAULT (NULL) FOR [CATEDOJ]
GO

ALTER TABLE [dbo].[EMPLOYEEMASTER] ADD  CONSTRAINT [DF_EMPLOYEEMASTER_CATEDOC]  DEFAULT (NULL) FOR [CATEDOC]
GO

ALTER TABLE [dbo].[EMPLOYEEMASTER] ADD  CONSTRAINT [DF_EMPLOYEEMASTER_CATEDOR]  DEFAULT (NULL) FOR [CATEDOR]
GO

ALTER TABLE [dbo].[EMPLOYEEMASTER] ADD  CONSTRAINT [DF_EMPLOYEEMASTER_CATESTATUS]  DEFAULT ((0)) FOR [CATESTATUS]
GO

ALTER TABLE [dbo].[EMPLOYEEMASTER] ADD  CONSTRAINT [DF_EMPLOYEEMASTER_CATECODE]  DEFAULT (NULL) FOR [CATECODE]
GO

ALTER TABLE [dbo].[EMPLOYEEMASTER] ADD  CONSTRAINT [DF_EMPLOYEEMASTER_LMUSRID]  DEFAULT ((0)) FOR [LMUSRID]
GO

ALTER TABLE [dbo].[EMPLOYEEMASTER] ADD  CONSTRAINT [DF_EMPLOYEEMASTER_DISPSTATUS]  DEFAULT ((0)) FOR [DISPSTATUS]
GO

ALTER TABLE [dbo].[EMPLOYEEMASTER] ADD  CONSTRAINT [DF_EMPLOYEEMASTER_PRCSDATE]  DEFAULT (NULL) FOR [PRCSDATE]
GO

ALTER TABLE [dbo].[EMPLOYEEMASTER] ADD  CONSTRAINT [DF_EMPLOYEEMASTER_REGNID]  DEFAULT ((0)) FOR [REGNID]
GO


