USE [MCT_ERP]
GO

/****** Object:  Table [dbo].[EMPTY_GATEOUTDETAIL]    Script Date: 05/03/2022 16:43:12 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[EMPTY_GATEOUTDETAIL](
	[GODID] [int] IDENTITY(1,1) NOT NULL ,
	[COMPYID] [int] NOT NULL CONSTRAINT [DF_EMPTY_GATEOUTDETAIL_COMPYID]  DEFAULT ((0)),
	[SDPTID] [int] NOT NULL CONSTRAINT [DF_EMPTY_GATEOUTDETAIL_SDPTID]  DEFAULT ((0)),
	[REGSTRID] [int] NOT NULL CONSTRAINT [DF_EMPTY_GATEOUTDETAIL_REGSTRID]  DEFAULT ((0)),
	[GODATE] [smalldatetime] NOT NULL CONSTRAINT [DF_EMPTY_GATEOUTDETAIL_GODATE]  DEFAULT (NULL),
	[GOTIME] [datetime] NOT NULL CONSTRAINT [DF_EMPTY_GATEOUTDETAIL_GOTIME]  DEFAULT (NULL),
	[GONO] [int] NOT NULL CONSTRAINT [DF_EMPTY_GATEOUTDETAIL_GONO]  DEFAULT ((0)),
	[GODNO] [varchar](15) NOT NULL CONSTRAINT [DF_EMPTY_GATEOUTDETAIL_GODNO]  DEFAULT (NULL),
	[GIDID] [int] NULL CONSTRAINT [DF_EMPTY_GATEOUTDETAIL_GIDID]  DEFAULT ((0)),
	[TRANDID] [int] NULL CONSTRAINT [DF_EMPTY_GATEOUTDETAIL_TRANDID]  DEFAULT ((0)),
	[VHLNO] [varchar](20) NULL CONSTRAINT [DF_EMPTY_GATEOUTDETAIL_VHLNO]  DEFAULT (NULL),
	[GDRVNAME] [varchar](50) NULL CONSTRAINT [DF_EMPTY_GATEOUTDETAIL_GDRVNAME]  DEFAULT (NULL),
	[CHASNAME] [varchar](50) NULL CONSTRAINT [DF_EMPTY_GATEOUTDETAIL_CHASNAME]  DEFAULT (NULL),
	[GOBTYPE] [smallint] NULL CONSTRAINT [DF_EMPTY_GATEOUTDETAIL_GOBTYPE]  DEFAULT ((0)),
	[CHAID] [int] NOT NULL CONSTRAINT [DF_EMPTY_GATEOUTDETAIL_CHAID]  DEFAULT ((0)),
	[LSEALNO] [varchar](25) NULL CONSTRAINT [DF_EMPTY_GATEOUTDETAIL_LSEALNO]  DEFAULT (NULL),
	[SSEALNO] [varchar](25) NULL CONSTRAINT [DF_EMPTY_GATEOUTDETAIL_SSEALNO]  DEFAULT (NULL),	
	[GOQTY] [numeric](18, 4) NULL CONSTRAINT [DF_EMPTY_GATEOUTDETAIL_GOQTY]  DEFAULT ((0)),
	[OTDID] [int] NULL CONSTRAINT [DF_EMPTY_GATEOUTDETAIL_OTDID]  DEFAULT ((0)),
	[OTDNO] [varchar](10) NULL CONSTRAINT [DF_EMPTY_GATEOUTDETAIL_OTDNO]  DEFAULT (NULL),
	[CONTNRFID] [int] NULL CONSTRAINT [DF_EMPTY_GATEOUTDETAIL_CONTNRFID]  DEFAULT ((0)),
	[BOOKID] [int] NULL CONSTRAINT [DF_EMPTY_GATEOUTDETAIL_BOOKID]  DEFAULT ((0)),
	[GOPLCNAME] [varchar](100) NULL CONSTRAINT [DF_EMPTY_GATEOUTDETAIL_GOPLCNAME]  DEFAULT (NULL),
	[GOBKGNO] [varchar](50) NULL CONSTRAINT [DF_EMPTY_GATEOUTDETAIL_GOBKGNO]  DEFAULT (NULL),
	[GOEGMNO] [varchar](20) NULL CONSTRAINT [DF_EMPTY_GATEOUTDETAIL_GOEGMNO]  DEFAULT (NULL),
	[OVSLID] [int] NULL CONSTRAINT [DF_EMPTY_GATEOUTDETAIL_OVSLID]  DEFAULT ((0)),
	[OVSLNAME] [varchar](100) NULL CONSTRAINT [DF_EMPTY_GATEOUTDETAIL_OVSLNAME]  DEFAULT (NULL),
	[OVOYNO] [varchar](10) NULL CONSTRAINT [DF_EMPTY_GATEOUTDETAIL_OVOYNO]  DEFAULT (NULL),
	[GOREMRKS] [varchar](100) NULL CONSTRAINT [DF_EMPTY_GATEOUTDETAIL_GOREMRKS]  DEFAULT (NULL),
	[OTRNSPRTNAME] [varchar](100) NULL CONSTRAINT [DF_EMPTY_GATEOUTDETAIL_OTRNSPRTNAME]  DEFAULT (NULL),
	[GBKDID] [int] NULL CONSTRAINT [DF_EMPTY_GATEOUTDETAIL_GBKDID]  DEFAULT ((0)),
	[GOFORM13NO] [varchar](50) NULL CONSTRAINT [DF_EMPTY_GATEOUTDETAIL_GOFORM13NO]  DEFAULT (NULL),
	[GOPODDETL] [varchar](100) NULL CONSTRAINT [DF_EMPTY_GATEOUTDETAIL_GOPODDETL]  DEFAULT (NULL),
	[GOISOCODE] [varchar](10) NULL CONSTRAINT [DF_EMPTY_GATEOUTDETAIL_GOPODDETL1]  DEFAULT (NULL),
	[GOSALEDATE] [smalldatetime] NULL CONSTRAINT [DF_EMPTY_GATEOUTDETAIL_GOSALEDATE]  DEFAULT (NULL),
	[GOSAILDATE] [smalldatetime] NULL CONSTRAINT [DF_EMPTY_GATEOUTDETAIL_GOSAILDATE]  DEFAULT (NULL),
	[GOASIS_TYPE] [int] NOT NULL CONSTRAINT [DF_EMPTY_GATEOUTDETAIL_GOASIS_TYPE]  DEFAULT ((0)),
	[CUSRID] [varchar](50) NULL CONSTRAINT [DF_EMPTY_GATEOUTDETAIL_CUSRID]  DEFAULT (('0')),
	[LMUSRID] [varchar](50) NULL CONSTRAINT [DF_EMPTY_GATEOUTDETAIL_LMUSRID]  DEFAULT (('0')),
	[DISPSTATUS] [smallint] NULL CONSTRAINT [DF_EMPTY_GATEOUTDETAIL_DISPSTATUS]  DEFAULT ((0)),
	[PRCSDATE] [datetime] NULL CONSTRAINT [DF_EMPTY_GATEOUTDETAIL_PRCSDATE]  DEFAULT (NULL),
 CONSTRAINT [PK_EMPTY_GATEOUTDETAIL] PRIMARY KEY CLUSTERED 
(
	[GODID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


