USE [MCT_ERP]
GO

/****** Object:  Table [dbo].[EMPTY_SLABMASTER]    Script Date: 28/02/2022 12:07:40 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[EMPTY_SLABMASTER](
	[SLABMID] [int] IDENTITY(1,1) NOT NULL,
	[COMPYID] [int] NOT NULL,
	[SLABMDATE] [smalldatetime] NOT NULL,
	[SLABTID] [int] NOT NULL,
	[TARIFFMID] [int] NOT NULL,
	[STMRID] [int] NOT NULL,
	[CHRGETYPE] [smallint] NOT NULL,
	[CONTNRSID] [int] NOT NULL,
	[SDTYPE] [smallint] NOT NULL,
	[YRDTYPE] [smallint] NOT NULL ,
	[HTYPE] [smallint] NOT NULL,
	[WTYPE] [smallint] NOT NULL,
	[SDPTTYPEID] [int] NOT NULL DEFAULT ((0)),
	[SLABMIN] [numeric](18, 2) NOT NULL,
	[SLABMAX] [numeric](18, 2) NOT NULL,
	[SLABAMT] [numeric](18, 2) NOT NULL,
	[CUSRID] [varchar](50) NOT NULL,
	[LMUSRID] [varchar](50) NOT NULL,
	[DISPSTATUS] [smallint] NOT NULL,
	[PRCSDATE] [datetime] NOT NULL,
 CONSTRAINT [PK_EMPTY_SLABMASTER] PRIMARY KEY CLUSTERED 
(
	[SLABMID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[EMPTY_SLABMASTER] ADD  CONSTRAINT [DF_EMPTY_SLABMASTER_COMPYID]  DEFAULT ((0)) FOR [COMPYID]
GO

ALTER TABLE [dbo].[EMPTY_SLABMASTER] ADD  CONSTRAINT [DF_EMPTY_SLABMASTER_SLABMDATE]  DEFAULT (NULL) FOR [SLABMDATE]
GO

ALTER TABLE [dbo].[EMPTY_SLABMASTER] ADD  CONSTRAINT [DF_EMPTY_SLABMASTER_SLABTID]  DEFAULT ((0)) FOR [SLABTID]
GO

ALTER TABLE [dbo].[EMPTY_SLABMASTER] ADD  CONSTRAINT [DF_EMPTY_SLABMASTER_TARIFFMID]  DEFAULT ((0)) FOR [TARIFFMID]
GO

ALTER TABLE [dbo].[EMPTY_SLABMASTER] ADD  CONSTRAINT [DF_EMPTY_SLABMASTER_STMRID]  DEFAULT ((0)) FOR [STMRID]
GO

ALTER TABLE [dbo].[EMPTY_SLABMASTER] ADD  CONSTRAINT [DF_EMPTY_SLABMASTER_CHRGETYPE]  DEFAULT ((0)) FOR [CHRGETYPE]
GO

ALTER TABLE [dbo].[EMPTY_SLABMASTER] ADD  CONSTRAINT [DF_EMPTY_SLABMASTER_CONTNRSID]  DEFAULT ((0)) FOR [CONTNRSID]
GO

ALTER TABLE [dbo].[EMPTY_SLABMASTER] ADD  CONSTRAINT [DF_EMPTY_SLABMASTER_SDTYPE]  DEFAULT ((0)) FOR [SDTYPE]
GO

ALTER TABLE [dbo].[EMPTY_SLABMASTER] ADD  CONSTRAINT [DF_EMPTY_SLABMASTER_YRDTYPE]  DEFAULT ((0)) FOR [YRDTYPE]
GO

ALTER TABLE [dbo].[EMPTY_SLABMASTER] ADD  CONSTRAINT [DF_EMPTY_SLABMASTER_HTYPE]  DEFAULT ((0)) FOR [HTYPE]
GO

ALTER TABLE [dbo].[EMPTY_SLABMASTER] ADD  CONSTRAINT [DF_EMPTY_SLABMASTER_WTYPE]  DEFAULT ((0)) FOR [WTYPE]
GO

ALTER TABLE [dbo].[EMPTY_SLABMASTER] ADD  CONSTRAINT [DF_EMPTY_SLABMASTER_SLABMIN]  DEFAULT ((0)) FOR [SLABMIN]
GO

ALTER TABLE [dbo].[EMPTY_SLABMASTER] ADD  CONSTRAINT [DF_EMPTY_SLABMASTER_SLABMAX]  DEFAULT ((0)) FOR [SLABMAX]
GO

ALTER TABLE [dbo].[EMPTY_SLABMASTER] ADD  CONSTRAINT [DF_EMPTY_SLABMASTER_SLABAMT]  DEFAULT ((0)) FOR [SLABAMT]
GO

ALTER TABLE [dbo].[EMPTY_SLABMASTER] ADD  CONSTRAINT [DF_EMPTY_SLABMASTER_CUSRID]  DEFAULT ('') FOR [CUSRID]
GO

ALTER TABLE [dbo].[EMPTY_SLABMASTER] ADD  CONSTRAINT [DF_EMPTY_SLABMASTER_LMUSRID]  DEFAULT ('') FOR [LMUSRID]
GO

ALTER TABLE [dbo].[EMPTY_SLABMASTER] ADD  CONSTRAINT [DF_EMPTY_SLABMASTER_DISPSTATUS]  DEFAULT ((0)) FOR [DISPSTATUS]
GO

ALTER TABLE [dbo].[EMPTY_SLABMASTER] ADD  CONSTRAINT [DF_EMPTY_SLABMASTER_PRCSDATE]  DEFAULT (NULL) FOR [PRCSDATE]
GO


