USE [MCT_ERP]
GO

/****** Object:  Table [dbo].[EMPTY_GATEINDETAIL]    Script Date: 03/03/2022 18:02:03 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[EMPTY_GATEINDETAIL](
	[GIDID] [int] Identity(1,1) NOT NULL,
	[COMPYID] [int] NOT NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_COMPYID]  DEFAULT ((0)),
	[SDPTID] [int] NOT NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_SDPTID]  DEFAULT ((0)),
	[GIDATE] [smalldatetime] NOT NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_GIDATE]  DEFAULT (NULL),
	[GITIME] [datetime] NOT NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_GITIME]  DEFAULT (NULL),
	[GICCTLDATE] [smalldatetime] NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_GICCTLDATE]  DEFAULT (NULL),
	[GICCTLTIME] [datetime] NOT NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_GICCTLTIME]  DEFAULT (NULL),
	[GINO] [int] NOT NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_GINO]  DEFAULT ((0)),
	[GIDNO] [varchar](15) NOT NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_GIDNO]  DEFAULT (NULL),
	[GIVHLTYPE] [smallint] NOT NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_GIVHLTYPE]  DEFAULT ((0)),
	[TRNSPRTID] [int] NOT NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_TRNSPRTID]  DEFAULT ((0)),
	[TRNSPRTNAME] [varchar](100) NOT NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_TRNSPRTNAME]  DEFAULT (NULL),
	[VHLNO] [varchar](15) NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_VHLNO]  DEFAULT (NULL),
	[DRVNAME] [varchar](100) NOT NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_DRVNAME]  DEFAULT (NULL),
	[GPREFNO] [varchar](15) NULL,
	[IMPRTID] [int] NOT NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_IMPRTID]  DEFAULT ((0)),
	[IMPRTNAME] [varchar](100) NOT NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_IMPRTNAME]  DEFAULT (NULL),
	[STMRID] [int] NOT NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_STMRID]  DEFAULT ((0)),
	[STMRNAME] [varchar](100) NOT NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_STMRNAME]  DEFAULT (NULL),
	[CONTNRTID] [int] NOT NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_CONTNRTID]  DEFAULT ((0)),
	[CONTNRID] [int] NOT NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_CONTNRID]  DEFAULT ((0)),
	[CONTNRSID] [int] NOT NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_CONTNRSID]  DEFAULT ((0)),
	[CONTNRNO] [varchar](15) NOT NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_CONTNRNO]  DEFAULT (NULL),
	[LPSEALNO] [varchar](50) NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_LPSEALNO]  DEFAULT (NULL),
	[CSEALNO] [varchar](15) NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_CSEALNO]  DEFAULT (NULL),
	[YRDID] [int] NOT NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_YRDID]  DEFAULT ((0)),
	[VSLID] [int] NOT NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_VSLID]  DEFAULT ((0)),
	[VSLNAME] [varchar](100) NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_VSLNAME]  DEFAULT (NULL),
	[VOYNO] [varchar](10) NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_VOYNO]  DEFAULT (NULL),
	[PRDTGID] [int] NOT NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_PRDTGID]  DEFAULT ((0)),
	[PRDTDESC] [varchar](100) NOT NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_PRDTDESC]  DEFAULT (NULL),
	[UNITID] [int] NOT NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_UNITID]  DEFAULT ((0)),
	[GPWGHT] [numeric](18, 4) NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_GPWGHT]  DEFAULT ((0)),
	[IGMNO] [varchar](15) NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_IGMNO]  DEFAULT (NULL),
	[GPLNO] [varchar](15) NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_GPLNO]  DEFAULT ((0)),
	[GPWTYPE] [smallint] NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_GPWTYPE]  DEFAULT ((0)),
	[GPSTYPE] [smallint] NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_GPSTYPE]  DEFAULT ((0)),
	[GPETYPE] [smallint] NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_GPETYPE]  DEFAULT ((0)),
	[BOEDID] [int] NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_BOEDID]  DEFAULT ((0)),
	[INVDID] [int] NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_INVDID]  DEFAULT ((0)),
	[RGIDID] [int] NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_RGIDID]  DEFAULT ((0)),
	[GIREMKRS] [varchar](100) NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_GIREMKRS]  DEFAULT (NULL),
	[SLOTID] [int] NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_SLOTID]  DEFAULT ((0)),	
	[GPEAMT] [numeric](18, 2) NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_GPEAMT]  DEFAULT ((0)),
	[CHAID] [int] NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_CHAID]  DEFAULT ((0)),
	[CHANAME] [varchar](100) NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_CHANAME]  DEFAULT (NULL),
	[AVHLNO] [varchar](15) NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_AVHLNO]  DEFAULT (NULL),
	[GPNOP] [numeric](18, 2) NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_GPNOP]  DEFAULT ((0)),
	[PRDTTID] [int] NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_PRDTTID]  DEFAULT ((0)),
	[GIISOCODE] [varchar](10) NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_GIISOCODE]  DEFAULT (NULL),
	[GIDMGDESC] [varchar](200) NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_GIDMGDESC]  DEFAULT (NULL),
	[NGIDID] [int] NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_NGIDID]  DEFAULT ((0)),
	[GPNWGHT] [numeric](18, 4) NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_GPNWGHT]  DEFAULT ((0)),
	[GPGWGHT] [numeric](18, 4) NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_GPGWGHT]  DEFAULT ((0)),
	[GPCBM] [numeric](18, 4) NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_GPCBM]  DEFAULT ((0)),
	[GPLENGTH] [numeric](18, 4) NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_GPLENGTH]  DEFAULT ((0)),
	[GPWIDTH] [numeric](18, 4) NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_GPWIDTH]  DEFAULT ((0)),
	[GPHEIGHT] [numeric](18, 4) NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_GPHEIGHT]  DEFAULT ((0)),
	[GPBLNO] [varchar](25) NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_GPBLNO]  DEFAULT (NULL),
	[GPAAMT] [numeric](18, 2) NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_GPAAMT]  DEFAULT ((0)),
	[CLNTID] [int] NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_CLNTID]  DEFAULT ((0)),
	[CLNTNAME] [varchar](100) NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_CLNTNAME]  DEFAULT ('-'),
	[SHPRNAME] [varchar](100) NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_SHPRNAME]  DEFAULT ('-'),
	[GPPLCNAME] [varchar](100) NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_GPPLCNAME]  DEFAULT (NULL),
	[GPTWGHT] [numeric](18, 4) NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_GPTWGHT]  DEFAULT ((0)),
	[CONTNRFID] [int] NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_CONTNRFID]  DEFAULT ((0)),
	[CONDTNID] [int] NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_CONDTNID]  DEFAULT ((0)),
	[GRADEID] [int] NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_GRADEID]  DEFAULT ((0)),
	[CNTNRSID] [int] NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_CNTNRSID]  DEFAULT ((0)),
	[GISDMDATE] [smalldatetime] NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_GISDMDATE]  DEFAULT (NULL),
	[GISDMDESC] [varchar](200) NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_GISDMDESC]  DEFAULT (NULL),
	[GISAVDATE] [smalldatetime] NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_GISAVDATE]  DEFAULT (NULL),
	[GISAVDESC] [varchar](200) NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_GISAVDESC]  DEFAULT (NULL),
	[EGPSCITYPE] [smallint] NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_EGPSCITYPE]  DEFAULT ((0)),
	[EGPVTYPE] [smallint] NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_EGPVTYPE]  DEFAULT ((0)),
	[EGPVDATE] [smalldatetime] NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_EGPVDATE]  DEFAULT (NULL),
	[GIESTTID] [int] NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_GIESTTID]  DEFAULT ((0)),
	[GILTYPE] [int] NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_GILTYPE]  DEFAULT ((0)),
	[GISENDERNAME] [varchar](100) NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_GISENDERNAME]  DEFAULT (NULL),
	[GIENTRYNO] [varchar](100) NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_GISENDERNAME1]  DEFAULT (NULL),
	[GIMATERIAL] [varchar](25) NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_GIENTRYNO1]  DEFAULT (NULL),
	[GIMEASURE] [varchar](25) NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_GIMATERIAL5]  DEFAULT (NULL),
	[GIUNIT] [varchar](25) NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_GIMATERIAL4]  DEFAULT (NULL),
	[GICSC] [varchar](25) NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_GIMATERIAL3]  DEFAULT (NULL),
	[GILESSOR] [varchar](25) NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_GIMATERIAL2]  DEFAULT (NULL),
	[GILASTLOCTCODE] [varchar](25) NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_GIMATERIAL1]  DEFAULT (NULL),
	[GILASTLOCTDATE] [smalldatetime] NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_GILASTLOCTDATE]  DEFAULT (NULL),
	[LCONDTNID] [int] NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_LCONDTNID]  DEFAULT ((0)),
	[GAVINO] [int] NOT NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_GINO1]  DEFAULT ((0)),
	[LCNTNRSID] [int] NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_LCNTNRSID]  DEFAULT ((0)),
	[LGISAVDATE] [smalldatetime] NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_LGISAVDATE]  DEFAULT (NULL),
	[LGISAVDESC] [varchar](200) NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_LGISAVDESC]  DEFAULT (NULL),
	[CUSRID] [varchar](50) NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_CUSRID]  DEFAULT (('')),
	[LMUSRID] [varchar](50) NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_LMUSRID]  DEFAULT (('')),
	[DISPSTATUS] [smallint] NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_DISPSTATUS]  DEFAULT ((0)),
	[PRCSDATE] [datetime] NULL CONSTRAINT [DF_EMPTY_GATEINDETAIL_PRCSDATE]  DEFAULT (NULL),
 CONSTRAINT [PK_EMPTY_GATEINDETAIL] PRIMARY KEY CLUSTERED 
(
	[GIDID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


