USE [MCT_ERP]
GO

/****** Object:  Table [dbo].[EMPTY_GATEIN_BLOCK_DETAILS]    Script Date: 07/03/2022 13:21:16 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[EMPTY_GATEIN_BLOCK_DETAILS](
	[GBDID] [int] IDENTITY(1,1) NOT NULL,
	[COMPYID] [int] NOT NULL CONSTRAINT [DF_EMPTY_GATEIN_BLOCK_DETAILS_COMPYID]  DEFAULT ((0)),
	[SDPTID] [int] NOT NULL CONSTRAINT [DF_EMPTY_GATEIN_BLOCK_DETAILS_SDPTID]  DEFAULT ((0)),
	[REGSTRID] [int] NOT NULL CONSTRAINT [DF_EMPTY_GATEIN_BLOCK_DETAILS_REGSTRID]  DEFAULT ((0)),
	[GBDATE] [smalldatetime] NOT NULL CONSTRAINT [DF_EMPTY_GATEIN_BLOCK_DETAILS_GBDATE]  DEFAULT (NULL),
	[GBTIME] [datetime] NOT NULL CONSTRAINT [DF_EMPTY_GATEIN_BLOCK_DETAILS_GBTIME]  DEFAULT (NULL),
	[GBNO] [int] NOT NULL CONSTRAINT [DF_EMPTY_GATEIN_BLOCK_DETAILS_GBNO]  DEFAULT ((0)),
	[GBDNO] [varchar](15) NOT NULL CONSTRAINT [DF_EMPTY_GATEIN_BLOCK_DETAILS_GBDNO]  DEFAULT (NULL),
	[GIDID] [int] NULL CONSTRAINT [DF_EMPTY_GATEIN_BLOCK_DETAILS_GIDID]  DEFAULT ((0)),
	[GBTYPE] [smallint] NULL CONSTRAINT [DF_EMPTY_GATEIN_BLOCK_DETAILS_GBTYPE]  DEFAULT ((0)),
	[NARTN] [varchar](100) NULL CONSTRAINT [DF_EMPTY_GATEIN_BLOCK_DETAILS_NARTN]  DEFAULT (NULL),
	[CUSRID] [varchar](100) NULL CONSTRAINT [DF_EMPTY_GATEIN_BLOCK_DETAILS_CUSRID]  DEFAULT (('0')),
	[LMUSRID] [varchar](100) NULL CONSTRAINT [DF_EMPTY_GATEIN_BLOCK_DETAILS_LMUSRID]  DEFAULT (('0')),
	[DISPSTATUS] [smallint] NULL CONSTRAINT [DF_EMPTY_GATEIN_BLOCK_DETAILS_DISPSTATUS]  DEFAULT ((0)),
	[PRCSDATE] [datetime] NULL CONSTRAINT [DF_EMPTY_GATEIN_BLOCK_DETAILS_PRCSDATE]  DEFAULT (NULL),
	[GBUDATE] [smalldatetime] NULL CONSTRAINT [DF_EMPTY_GATEIN_BLOCK_DETAILS_GBUDATE]  DEFAULT (NULL),
	[UNARTN] [varchar](250) NULL CONSTRAINT [DF_EMPTY_GATEIN_BLOCK_DETAILS_UNARTN]  DEFAULT (NULL),
	[GBREFNO] [varchar](20) NULL CONSTRAINT [DF_EMPTY_GATEIN_BLOCK_DETAILS_GBREFNO]  DEFAULT (NULL),
	[STMRID] [int] NULL CONSTRAINT [DF_EMPTY_GATEIN_BLOCK_DETAILS_STMRID]  DEFAULT ((0)),
	[SHPRNAME] [varchar](100) NULL CONSTRAINT [DF_EMPTY_GATEIN_BLOCK_DETAILS_SHPRNAME]  DEFAULT (NULL),
 CONSTRAINT [PK_EMPTY_GATEIN_BLOCK_DETAILS] PRIMARY KEY CLUSTERED 
(
	[GBDID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


