USE [MCT_ERP]
GO

/****** Object:  Table [dbo].[LEASINGSLABMASTER]    Script Date: 01/03/2022 12:01:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[LEASINGSLABMASTER](
	[LSLABMID] [int] Identity(1,1) NOT NULL,
	[COMPYID] [int] NOT NULL CONSTRAINT [DF_LEASINGSLABMASTER_COMPYID]  DEFAULT ((0)),
	[LSLABMDATE] [smalldatetime] NOT NULL CONSTRAINT [DF_LEASINGSLABMASTER_RSLABMDATE]  DEFAULT (NULL),
	[TARIFFMID] [int] NOT NULL CONSTRAINT [DF_LEASINGSLABMASTER_TARIFFMID]  DEFAULT ((0)),
	[STMRID] [int] NOT NULL CONSTRAINT [DF_LEASINGSLABMASTER_STMRID]  DEFAULT ((0)),
	[COMPTID] [int] NOT NULL CONSTRAINT [DF_LEASINGSLABMASTER_RPRTID]  DEFAULT ((0)),
	[DMGID] [int] NOT NULL CONSTRAINT [DF_LEASINGSLABMASTER_DMGID]  DEFAULT ((0)),
	[LRPRID] [int] NOT NULL CONSTRAINT [DF_LEASINGSLABMASTER_LRPRID]  DEFAULT ((0)),
	[UNITID] [int] NOT NULL CONSTRAINT [DF_LEASINGSLABMASTER_UNITID]  DEFAULT ((0)),
	[LLENGTH] [numeric](18, 2) NOT NULL CONSTRAINT [DF_LEASINGSLABMASTER_LLENGTH]  DEFAULT ((0)),
	[LWIDTH] [numeric](18, 2) NOT NULL CONSTRAINT [DF_LEASINGSLABMASTER_LLENGTH1]  DEFAULT ((0)),
	[LSLABHRS] [numeric](18, 2) NOT NULL CONSTRAINT [DF_LEASINGSLABMASTER_RSLABHRS]  DEFAULT ((0)),
	[LSLABAMT] [numeric](18, 2) NOT NULL CONSTRAINT [DF_LEASINGSLABMASTER_RSLABHAMT]  DEFAULT ((0)),
	[PRICECODE] [varchar](25) NOT NULL CONSTRAINT [DF_LEASINGSLABMASTER_PRICECODE]  DEFAULT (NULL),
	[CUSRID] [varchar](100) NULL CONSTRAINT [DF_LEASINGSLABMASTER_CUSRID]  DEFAULT (('0')),
	[LMUSRID] [varchar](100) NULL CONSTRAINT [DF_LEASINGSLABMASTER_LMUSRID]  DEFAULT (('0')),
	[DISPSTATUS] [smallint] NOT NULL CONSTRAINT [DF_LEASINGSLABMASTER_DISPSTATUS]  DEFAULT ((0)),
	[PRCSDATE] [datetime] NOT NULL CONSTRAINT [DF_LEASINGSLABMASTER_PRCSDATE]  DEFAULT (NULL),
	
 CONSTRAINT [PK_LEASINGSLABMASTER] PRIMARY KEY CLUSTERED 
(
	[LSLABMID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


