
USE [MCT_ERP]
GO

/****** Object:  Table [dbo].[PRODUCTGROUPMASTER]    Script Date: 04/03/2022 13:37:05 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE PRODUCTGROUPMASTER(
	[PRDTGID] [int] IDENTITY(1,1) NOT NULL,
	[PRDTGDESC] [varchar](100) NOT NULL CONSTRAINT [DF_PRODUCTGROUPMASTER_PRDTGDESC]  DEFAULT (NULL),
	[PRDTGCODE] [varchar](25) NOT NULL CONSTRAINT [DF_PRODUCTGROUPMASTER_PRDTGCODE]  DEFAULT (NULL),
	[CUSRID] [varchar](100) NULL CONSTRAINT [DF_PRODUCTGROUPMASTER_CUSRID]  DEFAULT (('0')),
	[LMUSRID] [varchar](100) NULL CONSTRAINT [DF_PRODUCTGROUPMASTER_LMUSRID]  DEFAULT (('0')),
	[DISPSTATUS] [smallint] NULL CONSTRAINT [DF_PRODUCTGROUPMASTER_DISPSTATUS]  DEFAULT ((0)),
	[PRCSDATE] [datetime] NULL CONSTRAINT [DF_PRODUCTGROUPMASTER_PRCSDATE]  DEFAULT (NULL),
 CONSTRAINT [PK_PRODUCTGROUPMASTER] PRIMARY KEY CLUSTERED 
(
	[PRDTGID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


