USE [MCT_ERP]
GO

/****** Object:  Table [dbo].[SOFT_TABLE_DELETE_DETAIL]    Script Date: 23/02/2022 12:30:39 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SOFT_TABLE_DELETE_DETAIL](
	[TABDID] [int] NOT NULL CONSTRAINT [DF_SOFT_TABLE_DELETE_DETAIL_TABDID]  DEFAULT ((0)),
	[OPTNSTR] [varchar](100) NULL CONSTRAINT [DF_SOFT_TABLE_DELETE_DETAIL_OPTNSTR]  DEFAULT (NULL),
	[TABNAME] [varchar](250) NULL CONSTRAINT [DF_SOFT_TABLE_DELETE_DETAIL_TABNAME]  DEFAULT (NULL),
	[PFLDNAME] [varchar](100) NULL CONSTRAINT [DF_SOFT_TABLE_DELETE_DETAIL_PFLDNAME]  DEFAULT (NULL),
	[DCONDTNSTR] [varchar](100) NULL CONSTRAINT [DF_SOFT_TABLE_DELETE_DETAIL_DCONDTNSTR]  DEFAULT (NULL),
	[DISPDESC] [varchar](250) NULL CONSTRAINT [DF_SOFT_TABLE_DELETE_DETAIL_DISPDESC]  DEFAULT (NULL),
 CONSTRAINT [PK_SOFT_TABLE_DELETE_DETAIL] PRIMARY KEY CLUSTERED 
(
	[TABDID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


