USE [MCT_ERP]
GO

/****** Object:  Table [dbo].[STATEMASTER]    Script Date: 23/02/2022 14:04:55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[STATEMASTER](
	[STATEID] [int] IDENTITY(1,1) NOT NULL,
	[STATEDESC] [varchar](100) NOT NULL CONSTRAINT [DF_STATEMASTER_LOCTDESC]  DEFAULT (NULL),
	[STATECODE] [varchar](15) NOT NULL CONSTRAINT [DF_STATEMASTER_LOCTCODE]  DEFAULT (NULL),
	[STATETYPE] [smallint] NOT NULL CONSTRAINT [DF_STATEMASTER_STATETYPE]  DEFAULT ((0)),
	[CUSRID] [varchar](100) NOT NULL CONSTRAINT [DF_STATEMASTER_CUSRID]  DEFAULT ((NULL)),
	[LMUSRID] [varchar](100) NULL CONSTRAINT [DF_STATEMASTER_LMUSRID]  DEFAULT (('')),
	[DISPSTATUS] [smallint] NOT NULL CONSTRAINT [DF_STATEMASTER_DISPSTATUS]  DEFAULT ((0)),
	[PRCSDATE] [datetime] NOT NULL CONSTRAINT [DF_STATEMASTER_PRCSDATE]  DEFAULT (NULL),
 CONSTRAINT [PK_STATEMASTER] PRIMARY KEY CLUSTERED 
(
	[STATEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


