USE [MCT_ERP]
GO

/****** Object:  Table [dbo].[TRANSACTION_DAYEND_MASTER]    Script Date: 28/02/2022 11:29:34 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TRANSACTION_DAYEND_MASTER](
	[COMPYID] [int] NOT NULL CONSTRAINT [DF_TRANSACTION_DAYEND_MASTER_COMPYID]  DEFAULT ((0)),
	[CUSRID] [int] NOT NULL CONSTRAINT [DF_TRANSACTION_DAYEND_MASTER_CUSRID]  DEFAULT ((0)),
	[TRANDATE] [datetime] NOT NULL CONSTRAINT [DF_TRANSACTION_DAYEND_MASTER_TRANDATE]  DEFAULT (NULL),
	[TRANNDATE] [datetime] NOT NULL CONSTRAINT [DF_TRANSACTION_DAYEND_MASTER_TRANNDATE]  DEFAULT (NULL)
) ON [PRIMARY]

GO
