USE [MCT_ERP]
GO

/****** Object:  Table [dbo].[UNITMASTER]    Script Date: 28/02/2022 19:23:16 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[UNITMASTER](
	[UNITID] [int] IDENTITY(1,1) NOT NULL,
	[UNITDESC] [varchar](100) NOT NULL CONSTRAINT [DF_UNITMASTER_UNITDESC]  DEFAULT (NULL),
	[UNITCODE] [varchar](15) NOT NULL CONSTRAINT [DF_UNITMASTER_UNITCODE]  DEFAULT (NULL),
	[CUSRID] [varchar](100) NOT NULL CONSTRAINT [DF_UNITMASTER_CUSRID]  DEFAULT (('0')),
	[LMUSRID] [varchar](100) NULL CONSTRAINT [DF_UNITMASTER_LMUSRID]  DEFAULT (('0')),
	[DISPSTATUS] [smallint] NOT NULL CONSTRAINT [DF_UNITMASTER_DISPSTATUS]  DEFAULT ((0)),
	[PRCSDATE] [datetime] NOT NULL CONSTRAINT [DF_UNITMASTER_PRCSDATE]  DEFAULT (NULL),
 CONSTRAINT [PK_UNITMASTER] PRIMARY KEY CLUSTERED 
(
	[UNITID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


