USE [MCT_ERP]
GO

/****** Object:  View [dbo].[VW_EMPTY_GATEIN_COTAINER_DETAILS]    Script Date: 09/03/2022 11:53:05 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




ALTER VIEW [dbo].[VW_EMPTY_GATEIN_COTAINER_DETAILS]
AS
SELECT     TOP 100 PERCENT MAX(dbo.EMPTY_GATEINDETAIL.GIDID) AS GIDID, dbo.EMPTY_GATEINDETAIL.CONTNRNO,GILTYPE,STMRID,STMRNAME
FROM         dbo.EMPTY_GATEINDETAIL  LEFT OUTER JOIN
                      dbo.EMPTY_GATEOUTDETAIL ON dbo.EMPTY_GATEINDETAIL.GIDID = dbo.EMPTY_GATEOUTDETAIL.GIDID
WHERE     (ISNULL(dbo.EMPTY_GATEOUTDETAIL.GIDID, 0) = 0) AND (dbo.EMPTY_GATEINDETAIL.SDPTID = 8) AND EMPTY_GATEINDETAIL.DISPSTATUS=0
GROUP BY CONTNRNO,GILTYPE,STMRID,STMRNAME
ORDER BY dbo.EMPTY_GATEINDETAIL.CONTNRNO






GO


