USE [MCT_ERP]
GO

/****** Object:  View [dbo].[VW_USER_DETAILS]    Script Date: 26/02/2022 15:20:05 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[VW_EMPLOYEE_DETAILS]
AS
SELECT  EMPLOYEEMASTER.CATEID,EMPLOYEEMASTER.CATENAME,EMPLOYEEMASTER.DEPTID,DEPARTMENTMASTER.DEPTDESC,
        EMPLOYEEMASTER.DSGNID,DESIGNATIONMASTER.DSGNDESC 
FROM   EMPLOYEEMASTER (NOLOCK) INNER JOIN 
       DEPARTMENTMASTER (NOLOCK) ON EMPLOYEEMASTER.DEPTID = DEPARTMENTMASTER.DEPTID INNER JOIN 
	   DESIGNATIONMASTER (NOLOCK) ON EMPLOYEEMASTER.DSGNID = DESIGNATIONMASTER.DSGNID  
                         



GO


