USE [MCT_ERP]
GO

/****** Object:  View [dbo].[VW_IMPORT_RATECARDMASTER_FLX_ASSGN_01]    Script Date: 28/02/2022 11:28:09 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VW_IMPORT_RATECARDMASTER_FLX_ASSGN_01]
AS
SELECT     TOP (100) PERCENT dbo.EMPTY_SLABMASTER.SLABTID, dbo.EMPTY_SLABMASTER.TARIFFMID, dbo.EMPTY_SLABMASTER.STMRID, dbo.EMPTY_SLABMASTER.CHRGETYPE, 
                      dbo.EMPTY_SLABMASTER.CONTNRSID, dbo.EMPTY_SLABMASTER.SDTYPE, dbo.EMPTY_SLABMASTER.YRDTYPE, dbo.EMPTY_SLABMASTER.HTYPE, dbo.EMPTY_SLABMASTER.WTYPE, 
                      MAX(dbo.EMPTY_SLABMASTER.SLABMDATE) AS XTRANSDATE
FROM         dbo.EMPTY_TARIFFMASTER INNER JOIN
                      dbo.EMPTY_SLABMASTER ON dbo.EMPTY_TARIFFMASTER.TARIFFMID = dbo.EMPTY_SLABMASTER.TARIFFMID
WHERE     (dbo.EMPTY_SLABMASTER.SLABMDATE <=
                          (SELECT     MAX(TRANNDATE) AS Expr1
                            FROM          dbo.TRANSACTION_DAYEND_MASTER))
GROUP BY dbo.EMPTY_SLABMASTER.TARIFFMID, dbo.EMPTY_SLABMASTER.SLABTID, dbo.EMPTY_SLABMASTER.STMRID, dbo.EMPTY_SLABMASTER.CHRGETYPE, dbo.EMPTY_SLABMASTER.CONTNRSID, 
                      dbo.EMPTY_SLABMASTER.SDTYPE, dbo.EMPTY_SLABMASTER.YRDTYPE, dbo.EMPTY_SLABMASTER.HTYPE, dbo.EMPTY_SLABMASTER.WTYPE
ORDER BY dbo.EMPTY_SLABMASTER.TARIFFMID


GO