



ALTER VIEW [dbo].[VW_EMPTY_ESTIMATE_GATEIN_CTRL_ASSGN]
AS
SELECT  DISTINCT  dbo.EMPTY_GATEINDETAIL.GIDID, dbo.EMPTY_GATEINDETAIL.SDPTID, dbo.EMPTY_GATEINDETAIL.CONTNRNO, dbo.CONTAINERSIZEMASTER.CONTNRSDESC, 
                  dbo.CONTAINERTYPEMASTER.CONTNRTDESC, CONVERT(varchar(10), dbo.EMPTY_GATEINDETAIL.GIDATE, 103) as GIDATE, --dbo.EMPTY_GATEINDETAIL.GIDATE,
				  CONVERT(varchar(10), dbo.EMPTY_GATEINDETAIL.GICCTLDATE, 103) as GICCTLDATE,-- dbo.EMPTY_GATEINDETAIL.GICCTLDATE,
				  (CONVERT(VARCHAR(10), dbo.EMPTY_GATEINDETAIL.GITIME, 103) + ' '  + convert(VARCHAR(8), dbo.EMPTY_GATEINDETAIL.GITIME, 14)) as GITIME,--dbo.EMPTY_GATEINDETAIL.GITIME, 
				  isnull(dbo.EMPTY_GATEINDETAIL.VSLNAME,'') as VSLNAME, isnull(dbo.EMPTY_GATEINDETAIL.VOYNO,'') as VOYNO,dbo.EMPTY_GATEINDETAIL.GPTWGHT,
				  dbo.EMPTY_GATEINDETAIL.GPWGHT,dbo.EMPTY_GATEINDETAIL.STMRID, dbo.EMPTY_GATEINDETAIL.STMRNAME,dbo.EMPTY_GATEINDETAIL.CONTNRTID,
				  dbo.EMPTY_GATEINDETAIL.CONTNRSID,isnull(Convert(varchar(10),dbo.EMPTY_GATEIN_BLOCK_DETAILS.GBDATE,103),'') as GBDATE,  --dbo.EMPTY_GATEIN_BLOCK_DETAILS.GBDATE, 
				  isnull(dbo.EMPTY_GATEIN_BLOCK_DETAILS.NARTN,'') as NARTN,isnull(Convert(varchar(10),dbo.EMPTY_GATEIN_BLOCK_DETAILS.GBUDATE,103),'') as GBUDATE, -- dbo.EMPTY_GATEIN_BLOCK_DETAILS.GBUDATE, 
				  isnull(dbo.EMPTY_GATEIN_BLOCK_DETAILS.UNARTN,'') as UNARTN, dbo.CONTAINERSTATUSMASTER.CNTNRSCODE,isnull(Convert(varchar(10),dbo.EMPTY_GATEINDETAIL.GISAVDATE,103),'') as GISAVDATE, 
                  isnull(dbo.EMPTY_GATEINDETAIL.GISAVDESC,'') as GISAVDESC, isnull(Convert(varchar(10),dbo.EMPTY_GATEINDETAIL.GISDMDATE,103),'') as GISDMDATE,
				  isnull(dbo.EMPTY_GATEINDETAIL.GISDMDESC,'') as GISDMDESC,--dbo.EMPTY_GATEINDETAIL.GISDMDATE, dbo.EMPTY_GATEINDETAIL.GISDMDESC, 
                  dbo.CONDITIONMASTER.CONDTNDESC, dbo.EMPTY_GATEINDETAIL.CNTNRSID, isnull(dbo.EMPTY_GATEIN_BLOCK_DETAILS.GBDID,0) as  GBDID,
				  isnull(dbo.EMPTY_GATEIN_BLOCK_DETAILS.GBTYPE,0) as GBTYPE,dbo.EMPTY_GATEINDETAIL.GRADEID,isnull(dbo.EMPTY_GATEINDETAIL.LCONDTNID,0) as LCONDTNID, 
				  isnull(dbo.EMPTY_GATEINDETAIL.SHPRNAME,'') as SHPRNAME,dbo.EMPTY_GATEINDETAIL.CLNTNAME,GRADEMASTER.GRADEDESC,dbo.EMPTY_GATEINDETAIL.GIDNO,
				  CATEGORYMASTER.ACHEADID,CATEGORYMASTER.TARIFFMID,Isnull(CATEGORYMASTER.CATEACODE,'') as CATEACODE
        FROM      dbo.EMPTY_GATEINDETAIL (nolock) Inner Join  
		          dbo.CONTAINERSIZEMASTER  (nolock)  on dbo.EMPTY_GATEINDETAIL.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID Inner Join  
				  dbo.CONTAINERTYPEMASTER  (nolock)  on dbo.EMPTY_GATEINDETAIL.CONTNRTID = dbo.CONTAINERTYPEMASTER.CONTNRTID Left Outer Join  
				  dbo.CONDITIONMASTER  (nolock)  on dbo.EMPTY_GATEINDETAIL.CONDTNID = dbo.CONDITIONMASTER.CONDTNID Left Outer Join   
				  dbo.CONTAINERSTATUSMASTER  (nolock)  on dbo.EMPTY_GATEINDETAIL.CNTNRSID = dbo.CONTAINERSTATUSMASTER.CNTNRSID Left Outer Join   
				  dbo.EMPTY_GATEIN_BLOCK_DETAILS  (nolock)  on dbo.EMPTY_GATEINDETAIL.GIDID = dbo.EMPTY_GATEIN_BLOCK_DETAILS.GIDID Inner Join  
				  dbo.GRADEMASTER (nolock) on dbo.EMPTY_GATEINDETAIL.GRADEID = dbo.GRADEMASTER.GRADEID Inner Join  
				  dbo.CATEGORYMASTER (nolock) on dbo.EMPTY_GATEINDETAIL.STMRID = CATEGORYMASTER.CATEID   
	    WHERE     (dbo.EMPTY_GATEINDETAIL.SDPTID = 8) --and EMPTY_GATEINDETAIL.STMRID=19 and CATEGORYMASTER.ACHEADID=0




