USE [MCT_ERP]
GO

/****** Object:  View [dbo].[VW_IMPORT_RATECARDMASTER_FLX_ASSGN_02]    Script Date: 28/02/2022 11:27:31 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VW_EMPTY_RATECARDMASTER_FLX_ASSGN_02]
AS
SELECT     MAX(dbo.EMPTY_SLABMASTER.SLABMID) AS Expr1, dbo.VW_EMPTY_RATECARDMASTER_FLX_ASSGN_01.SLABTID, 
                      dbo.VW_EMPTY_RATECARDMASTER_FLX_ASSGN_01.TARIFFMID, dbo.VW_EMPTY_RATECARDMASTER_FLX_ASSGN_01.STMRID, 
                      dbo.VW_EMPTY_RATECARDMASTER_FLX_ASSGN_01.CHRGETYPE, dbo.VW_EMPTY_RATECARDMASTER_FLX_ASSGN_01.CONTNRSID, 
                      dbo.VW_EMPTY_RATECARDMASTER_FLX_ASSGN_01.SDTYPE, dbo.VW_EMPTY_RATECARDMASTER_FLX_ASSGN_01.YRDTYPE, 
                      dbo.VW_EMPTY_RATECARDMASTER_FLX_ASSGN_01.HTYPE, dbo.VW_EMPTY_RATECARDMASTER_FLX_ASSGN_01.WTYPE, 
                      dbo.VW_EMPTY_RATECARDMASTER_FLX_ASSGN_01.XTRANSDATE
FROM         dbo.EMPTY_SLABMASTER INNER JOIN
                      dbo.VW_EMPTY_RATECARDMASTER_FLX_ASSGN_01 ON dbo.EMPTY_SLABMASTER.TARIFFMID = dbo.VW_EMPTY_RATECARDMASTER_FLX_ASSGN_01.TARIFFMID AND 
                      dbo.EMPTY_SLABMASTER.SLABTID = dbo.VW_EMPTY_RATECARDMASTER_FLX_ASSGN_01.SLABTID AND  
                      dbo.EMPTY_SLABMASTER.SLABMDATE = dbo.VW_EMPTY_RATECARDMASTER_FLX_ASSGN_01.XTRANSDATE AND  					  
					   dbo.EMPTY_SLABMASTER.CONTNRSID = dbo.VW_EMPTY_RATECARDMASTER_FLX_ASSGN_01.CONTNRSID AND   
					   dbo.EMPTY_SLABMASTER.SDTYPE = dbo.VW_EMPTY_RATECARDMASTER_FLX_ASSGN_01.SDTYPE 
GROUP BY dbo.VW_EMPTY_RATECARDMASTER_FLX_ASSGN_01.SLABTID, dbo.VW_EMPTY_RATECARDMASTER_FLX_ASSGN_01.TARIFFMID, 
                      dbo.VW_EMPTY_RATECARDMASTER_FLX_ASSGN_01.STMRID, dbo.VW_EMPTY_RATECARDMASTER_FLX_ASSGN_01.CHRGETYPE, 
                      dbo.VW_EMPTY_RATECARDMASTER_FLX_ASSGN_01.CONTNRSID, dbo.VW_EMPTY_RATECARDMASTER_FLX_ASSGN_01.SDTYPE, 
                      dbo.VW_EMPTY_RATECARDMASTER_FLX_ASSGN_01.YRDTYPE, dbo.VW_EMPTY_RATECARDMASTER_FLX_ASSGN_01.HTYPE, 
                      dbo.VW_EMPTY_RATECARDMASTER_FLX_ASSGN_01.WTYPE, dbo.VW_EMPTY_RATECARDMASTER_FLX_ASSGN_01.XTRANSDATE
					  




GO
