USE [MCT_ERP]
GO

/****** Object:  View [dbo].[VW_GATEIN_GATEOUT_DETAIL_ASSIGN]    Script Date: 09/03/2022 16:09:52 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER OFF
GO



ALTER VIEW [dbo].[VW_GATEIN_GATEOUT_DETAIL_ASSIGN]
AS
SELECT     TOP 100 PERCENT dbo.EMPTY_GATEINDETAIL.GIDID AS GIDID, Convert(varchar(10), dbo.EMPTY_GATEINDETAIL.GIDATE, 103) AS GIDATE, 
           isnull(dbo.EMPTY_GATEINDETAIL.IMPRTNAME,'') AS IMPRTNAME,isnull(EMPTY_GATEINDETAIL.STMRID,0) as STMRID,
		   isnull(CATEGORYMASTER.CATENAME,'') AS STMRNAME,isnull(EMPTY_GATEINDETAIL.VHLNO,'') as VHLNO,
		   isnull(EMPTY_GATEINDETAIL.DRVNAME,'') as DRVNAME,isnull(EMPTY_GATEINDETAIL.TRNSPRTNAME,'') as TRNSPRTNAME,
		   isnull(EMPTY_GATEOUTDETAIL.OTRNSPRTNAME,'') as OTRNSPRTNAME, '' as HDATE,'' as HREASON,
		   '' as RDATE,'' as RREASON,GILTYPE,'' as SDATE,'' as GBSTATUS,dbo.EMPTY_GATEINDETAIL.CONTNRNO AS CONTNRNO,
		   dbo.CONTAINERSIZEMASTER.CONTNRSDESC, dbo.EMPTY_GATEINDETAIL.CONTNRTID,dbo.CONTAINERTYPEMASTER.CONTNRTDESC,
		   Isnull(Convert(varchar(10),dbo.EMPTY_GATEOUTDETAIL.GODATE,103),'') as GODATE
FROM         dbo.EMPTY_GATEINDETAIL (NOLOCK) INNER JOIN
                      dbo.CONTAINERSIZEMASTER (NOLOCK)  ON dbo.EMPTY_GATEINDETAIL.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID LEFT OUTER JOIN
                      dbo.EMPTY_GATEOUTDETAIL  (NOLOCK) ON dbo.EMPTY_GATEINDETAIL.GIDID = dbo.EMPTY_GATEOUTDETAIL.GIDID INNER JOIN 
					  dbo.CATEGORYMASTER (NOLOCK) ON  dbo.EMPTY_GATEINDETAIL.STMRID = dbo.CATEGORYMASTER.CATEID INNER JOIN 
					  dbo.CONTAINERTYPEMASTER (NOLOCK) ON dbo.EMPTY_GATEINDETAIL.CONTNRTID = dbo.CONTAINERTYPEMASTER.CONTNRTID 
ORDER BY dbo.EMPTY_GATEINDETAIL.CONTNRSID 


GO


