USE [MCT_ERP]
GO

/****** Object:  View [dbo].[VW_YARD_STEAMER_MAPPING_DETAIL_ASSIGN]    Script Date: 07/03/2022 16:09:25 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER OFF
GO



ALTER VIEW [dbo].[VW_YARD_STEAMER_MAPPING_DETAIL_ASSIGN]
AS
SELECT     TOP 100 PERCENT dbo.YARDMASTER.YRDID AS YRDID, YARDMASTER.YRDDESC AS YRDDESC, 
             STEAMERYARDMAPPINGDETAIL.STMRID,CATEGORYMASTER.CATENAME,CATELTYPE 
FROM         dbo.YARDMASTER (NOLOCK) INNER JOIN  
            STEAMERYARDMAPPINGDETAIL (NOLOCK) ON STEAMERYARDMAPPINGDETAIL.YRDID = YARDMASTER.YRDID INNER JOIN 
			CATEGORYMASTER (NOLOCK) ON STEAMERYARDMAPPINGDETAIL.STMRID = CATEGORYMASTER.CATEID   
where getdate() between STEAMERYARDMAPPINGDETAIL.EFFFRMDT and ISNULL(STEAMERYARDMAPPINGDETAIL.EFFTODT,getdate())


GO


