USE [MCT_ERP]
GO

/****** Object:  View [dbo].[VW_YARD_EMPLOYEE_MAPPING_DETAIL_ASSIGN]    Script Date: 08-03-2022 12:44:36 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER OFF
GO




ALTER VIEW [dbo].[VW_YARD_EMPLOYEE_MAPPING_DETAIL_ASSIGN]
AS
SELECT     TOP 100 PERCENT dbo.YARDMASTER.YRDID AS YRDID, YARDMASTER.YRDDESC AS YRDDESC, 
             EMPLOYEEYARDMAPPINGDETAIL.EMPID,EMPLOYEEMASTER.CATENAME , AspNetUsers.UserName
FROM         dbo.YARDMASTER (NOLOCK) INNER JOIN  
            EMPLOYEEYARDMAPPINGDETAIL (NOLOCK) ON EMPLOYEEYARDMAPPINGDETAIL.YRDID = YARDMASTER.YRDID INNER JOIN 
			EMPLOYEEMASTER (NOLOCK) ON EMPLOYEEYARDMAPPINGDETAIL.EMPID = EMPLOYEEMASTER.CATEID   join 
			AspNetUsers (nolock) on EMPLOYEEMASTER.CATEID   = AspNetUsers.EmpId
where getdate() between EMPLOYEEYARDMAPPINGDETAIL.EFFFRMDT and ISNULL(EMPLOYEEYARDMAPPINGDETAIL.EFFTODT,getdate())

GO


