/*insert into MCT_ERP..COMPANYMASTER (COMPNAME, COMPDNAME, COMPADDR, COMPPHNID, COMPPHN1, COMPPHN2, COMPPHN3, COMPPHN4, COMPCPRSN, COMPMAIL, COMPCODE, 
CUSRID, LMUSRID, DISPSTATUS, PRCSDATE, COMPCOFFTIME, COMPPDESC1, COMPPDESC2, COMPGSTNO)
select COMPNAME, COMPDNAME, COMPADDR, COMPPHNID, COMPPHN1, COMPPHN2, COMPPHN3, COMPPHN4, COMPCPRSN, COMPMAIL, COMPCODE, 
CUSRID, LMUSRID, DISPSTATUS, PRCSDATE, COMPCOFFTIME, COMPPDESC1, COMPPDESC2, COMPGSTNO
from mct..COMPANYMASTER
*/

select * from mct_erp..COMPANYACCOUNTINGDETAIL

update MCT_ERP..COMPANYMASTER 
set COMP_SMTP='', COMP_SMTP_PORT='', COMP_POP3='',COMP_POP3_PORT='', COMP_POLICY_NO ='', COMP_POLICY_DATE='2022-04-01', COMP_LUT_NO =''

SELECT AccountingYear.YRID, AccountingYear.YRDESC, * FROM AccountingYear
